# Originally written by Jonathan Larmour, Red Hat, Inc.
# Modify by lijian (@Sunnorth) for easy building.
# This file is in the public domain and may be used for any purpose

include $(PSROOT)/build_scripts/platform.mk


XCC           = $(PLATFORM)gcc
XCXX          = $(PLATFORM)g++
XLD           = $(PLATFORM)g++
XAR           = $(PLATFORM)ar
OBJCOPY       = objcopy
XAS           = $(PLATFORM)as

LINUX_PL      = y
LDFLAGS += -lstdc++
LDFLAGS += -lpthread
LDFLAGS += -pthread
LDFLAGS += -lrt

ifneq ($(PLATFORM), aarch64-linux-gnu-)
# aarch64 环境编译 无需-m64
#LDFLAGS += -m64
#COMMONFLAGS += -m64
endif

COMMONFLAGS += -w
COMMONFLAGS += -MD 
COMMONFLAGS += -g -rdynamic
COMMONFLAGS += -D_GNU_SOURCE
COMMONFLAGS += -fPIC
COMMONFLAGS += -fdiagnostics-color=always
COMMONFLAGS += -std=c++17
CFLAGS+=  $(COMMONFLAGS) $(INCFLAGS)
CXXFLAGS+= $(COMMONFLAGS) $(INCFLAGS) 

ifeq ($(xtest),y)
	CXXFLAGS += -DGTEST_EN
endif

INCFLAGS += -I$(PSROOT)/common
INCFLAGS += -I$(PSROOT)/common/if
INCFLAGS += -I$(PSROOT)/common/if_mc
INCFLAGS += -I$(PSROOT)/common/if_pl
INCFLAGS += -I$(PSROOT)/common/proto
INCFLAGS += -I$(PSROOT)/common/json2pb
INCFLAGS += -I$(PSROOT)
INCFLAGS += -I$(PSROOT)/platform
INCFLAGS += -I$(PSROOT)/drsu/proto
INCFLAGS += -I$(PSROOT)/drsu/perception_ai/include
INCFLAGS += -I$(PSROOT)/platform/openssl
INCFLAGS += -I$(PSROOT)/drsu/common
INCFLAGS += -I$(PSROOT)/drc/common
INCFLAGS += -I$(PSROOT)/drc/utils
INCFLAGS += -I$(PSROOT)/drc/utils/kafka
INCFLAGS += -I$(PSROOT)/drc/rctp/common
INCFLAGS += -I$(PSROOT)/drc/rctp/regc
INCFLAGS += -I$(PSROOT)/drc/rctp/recm
INCFLAGS += -I$(PSROOT)/drc/vtsm/utils
INCFLAGS += -I$(PSROOT)/drc/vtsm/recm
INCFLAGS += -I$(PSROOT)/drc/vtsm/regc
INCFLAGS += -I$(PSROOT)/drc/vtsm/common
INCFLAGS += -I/usr/local/include
INCFLAGS += -I$(PSROOT)/common/hdmap
INCFLAGS += -I$(PSROOT)/common/if_pl/nacos
INCFLAGS += -I$(PSROOT)/common/if_pl/pistache
INCFLAGS += -I$(PSROOT)/common/if_pl/mqtt
INCFLAGS += -I$(PSROOT)/common/if_pl/jsoncpp
INCFLAGS += -I$(PSROOT)/common/thread
INCFLAGS += -I$(PSROOT)/cloud/waypoint
INCFLAGS += -I$(PSROOT)/cloud/flyto
INCFLAGS += -I$(PSROOT)/cloud/track
INCFLAGS += -I$(PSROOT)/cloud/device
INCFLAGS += -I/usr/include/eigen3
INCFLAGS += -I/usr/include

vpath %.o $(BUILD_DIR)

%.o: %.c
	mkdir -p $(BUILD_DIR)/`dirname $<` 
	$(XCC) $(CFLAGS) -c -o $(BUILD_DIR)/$*.o  $< 

%.o: %.cpp
	mkdir -p $(BUILD_DIR)/`dirname $<` 
	$(XCXX) $(CXXFLAGS) -c -o $(BUILD_DIR)/$*.o  $< 

%.o: %.S
	mkdir -p $(BUILD_DIR)/`dirname $<` 
	$(XAS) -o $(BUILD_DIR)/$*.o  $< 

%.o: %.cxx
	mkdir -p $(BUILD_DIR)/`dirname $<` 
	$(XCXX) $(CXXFLAGS) -c -o $(BUILD_DIR)/$*.o  $< 
    
%.o: %.cc
	mkdir -p $(BUILD_DIR)/`dirname $<` 
	$(XCXX) $(CXXFLAGS) -c -o $(BUILD_DIR)/$*.o  $< 


OBJS = $(addprefix $(BUILD_DIR)/,$(patsubst %c,%o,$(OBJECT)))
MAKELIB = $(XAR) ru $(BUILD_DIR)/../$(TARGET) $(OBJS)
MAKELIBSO = $(XCXX) $(CXXFLAGS) -shared -o $(BUILD_DIR)/../$(TARGETSO) $(OBJS)
CLEANLIB = -rm -f $(OBJS)
