# Mostly written by Jonathan Larmour, Red Hat, Inc.
# Reference to ecos.mak added by John Dallaway, eCosCentric Limited, 2003-01-20
# This file is in the public domain and may be used for any purpose

# Usage:   
PSROOT = ../..
TARGET = libplroot_$(BUILDCOMMON).a
include $(PSROOT)/build_scripts/platform.mk

OBJECT += pf_cloud_root.o

include $(PSROOT)/build_scripts/staticlibrary.mk
