/********************************************************************
  Copyright (C), broadxt Inc  2019
  FileName: decl_event_drc_drsu.h
  Author: josephzhou      Version : v0.1         Date:2019-5-24
  Description:     define message Identities
  History:     
  <author>       <time>         <version >      <desc>
  josephzhou     2019/05/24     v0.1            build this moudle 
  josephzhou     2019/06/13     v0.1            add DRC&DRSU, DRC&DRCRM message ID
  liyafei        2020/03/25                     add wisdom freeway:1043~1050, 16409~16417
  liyafei        2020/06/13     v0.1            add video related:1059,1060,16426,16427
  note：only support three kinds of message: _REQ, _CFM, _IND, _RSP

        DRC<->ACU       0x0   ~0x3FF
        DRC<->DRSU      0x400 ~0x7FF
        DRC<->DRCRM     0x800 ~0xBFF
        DRC INTER       0x1000~0x3FFF
              
        DRSU<->DRC      0x4000~0x43FF
        DRSU INTER      0x5000~0x7FFF
              
        DRCRM<->DRC     0x8000~0x8FFF
        DRCRM INTER     0x9000~0xBFFF
        PLATFORM        0xFF00~0xFFFF
*******************************************************************/



/*----------DRC和DRSU交互消息定义---------*/
DECL_BEGIN(DRC_DRSU_BEGIN,         0, (EVENT_SEG_LEN*4)),//1024(0x400)
DECL_EVENT(DRC_DRSU_REG_RSP,                    0),
DECL_EVENT(DRC_DRSU_CFG_REQ,                    0),
DECL_EVENT(DRC_DRSU_HDM_UPDATE_REQ,             0),
DECL_EVENT(DRC_DRSU_SOFTWARE_UPDATE_REQ,        0),
DECL_EVENT(DRC_DRSU_ALARM_CRITICAL_RSP,         0),
DECL_EVENT(DRC_DRSU_ALARM_CLEAR_CFM,            0),
DECL_EVENT(DRC_DRSU_RESTART_IND,                0),
DECL_EVENT(DRC_DRSU_LOGUPLOAD_CFG_REQ,          0),
DECL_EVENT(DRC_DRSU_LOGSWICH_CFG_REQ,           0),
DECL_EVENT(DRC_DRSU_FANS_TMPRT_CFG_REQ,         0),
DECL_EVENT(DRC_DRSU_EQUIP_BOX_OPEN_ALARM_DISABLE_TIME_CFG_REQ,    0),
DECL_EVENT(DRC_DRSU_WORK_TIME_CFG_REQ,          0),
DECL_EVENT(DRC_DRSU_LOGLEVEL_CFG_REQ,           0),
DECL_EVENT(DRC_DRSU_LOGLEVEL_QUERY_REQ,         0),
DECL_EVENT(DRC_DRSU_TRAFFIC_WARNING_EVENT_START_REQ,    0),
DECL_EVENT(DRC_DRSU_TRAFFIC_WARNING_EVENT_UPDATE_REQ,   0),//1040(0x410)
DECL_EVENT(DRC_DRSU_TRAFFIC_WARNING_EVENT_END_REQ,      0),
DECL_EVENT(DRC_DRSU_START_VIDEO_PREVIEW_REQ,    0),
DECL_EVENT(DRC_DRSU_STOP_VIDEO_PREVIEW_REQ,     0),
DECL_EVENT(DRC_DRSU_VIDEO_REPORT_REQ,           0),
DECL_EVENT(DRC_DRSU_VIDEO_PTZ_CTRL_REQ,         0),
DECL_EVENT(DRC_DRSU_AI_CFG_REQ,                 0),
DECL_EVENT(DRC_DRSU_DEBUGFILE_UPLOAD_IMMEDIATELY_REQ,   0),
DECL_EVENT(DRC_DRSU_DEVICE_POWEROFF_REQ,        0),
DECL_EVENT(DRC_DRSU_DEVICE_POWERON_REQ,         0),
DECL_EVENT(DRC_DRSU_ALL_SENSOR_POWEROFF_REQ,    0),
DECL_EVENT(DRC_DRSU_ALL_SENSOR_POWERON_REQ,     0),
DECL_EVENT(DRC_DRSU_DATA_SYNC_REQ,              0),
DECL_EVENT(DRC_DRSU_DEVICE_STATUS_REPORT_RSP,   0),
DECL_EVENT(DRC_DRSU_ALL_DEVICE_STATUS_REPORT_RSP,   0),
DECL_EVENT(DRC_DRSU_IDLE_START_VIDEO_PREVIEW_REQ,   0), 
DECL_EVENT(DRC_DRSU_MODIFY_DRSU_VIDEO_DEFINITION_REQ,   0), //1056(0x420)
DECL_EVENT(DRC_DRSU_ALARM_RPT_PERIOD_CFG_REQ,       0),
DECL_EVENT(DRC_DRSU_NOT_RECEIVED_DATA_NOTIFY,       0),
/* 请在尾部（这里）追加，不要增删前面的枚举 */

/*----------DRSU和DRC交互消息定义---------*/
DECL_BEGIN(DRSU_DRC_BEGIN_MSG,         0, (EVENT_SEG_LEN*64)),//16384(0x4000)
DECL_EVENT(DRSU_DRC_REG_REQ,                    0),
DECL_EVENT(DRSU_DRC_HDM_UPDATE_CFM,             0),
DECL_EVENT(DRSU_DRC_HDM_UPDATE_IND,             0),
DECL_EVENT(DRSU_DRC_SOFTWARE_UPDATE_CFM,        0),
DECL_EVENT(DRSU_DRC_SOFTWARE_UPDATE_IND,        0),
DECL_EVENT(DRSU_DRC_ALARM_CRITICAL_REQ,         0),
DECL_EVENT(DRSU_DRC_ALARM_NORMAL_IND,           0),
DECL_EVENT(DRSU_DRC_ALARM_CLEAR_IND,            0),
DECL_EVENT(DRSU_DRC_RAW_DATA_INFO_IND,          0),
DECL_EVENT(DRSU_DRC_LOGUPLOAD_CFG_RSP,          0),
DECL_EVENT(DRSU_DRC_LOGSWITCH_CFG_RSP,          0),
DECL_EVENT(DRSU_DRC_LOG_FILE_RECORDINFO_IND,    0),
DECL_EVENT(DRSU_DRC_FANS_TMPRT_CFG_RSP,         0),
DECL_EVENT(DRSU_DRC_EQUIP_BOX_OPEN_ALARM_DISABLE_TIME_CFG_RSP,    0),
DECL_EVENT(DRSU_DRC_DEVICE_STATUS_REPORT,       0),
DECL_EVENT(DRSU_DRC_ALL_DEVICE_STATUS_REPORT,   0),//16400(0x4010)
DECL_EVENT(DRSU_DRC_WORK_TIME_CFG_RSP,          0),
DECL_EVENT(DRSU_DRC_LOGLEVEL_CFG_RSP,           0),
DECL_EVENT(DRSU_DRC_LOGLEVEL_QUERY_RSP,         0),
DECL_EVENT(DRSU_DRC_TRAFFIC_WARNING_EVENT_START_RSP,  0),
DECL_EVENT(DRSU_DRC_TRAFFIC_WARNING_EVENT_UPDATE_RSP, 0),
DECL_EVENT(DRSU_DRC_TRAFFIC_WARNING_EVENT_END_RSP,    0),
DECL_EVENT(DRSU_DRC_START_VIDEO_PREVIEW_RSP,    0),
DECL_EVENT(DRSU_DRC_STOP_VIDEO_PREVIEW_RSP,     0),
DECL_EVENT(DRSU_DRC_VIDEO_REPORT_RSP,           0),
DECL_EVENT(DRSU_DRC_VIDEO_PTZ_CTRL_RSP,         0), //16410(0x401a)
DECL_EVENT(DRSU_DRC_AI_CFG_RSP,                 0),
DECL_EVENT(DRSU_DRC_DEBUGFILE_UPLOAD_IMMEDIATELY_RSP,   0),
DECL_EVENT(DRSU_DRC_DEVICE_POWEROFF_RSP,        0),
DECL_EVENT(DRSU_DRC_DEVICE_POWERON_RSP,         0),
DECL_EVENT(DRSU_DRC_ALL_SENSOR_POWEROFF_RSP,    0),
DECL_EVENT(DRSU_DRC_ALL_SENSOR_POWERON_RSP,     0),//16416(0x4020)
DECL_EVENT(DRSU_DRC_EQUIP_BOX_TMPRT_REPORT_IND, 0),
DECL_EVENT(DRSU_DRC_CFG_RSP,                    0),
DECL_EVENT(DRSU_DRC_DATA_SYNC_RSP,              0),
DECL_EVENT(DRSU_DRC_IDLE_START_VIDEO_PREVIEW_RSP,       0),
DECL_EVENT(DRSU_DRC_MODIFY_DRSU_VIDEO_DEFINITION_RSP,   0),
DECL_EVENT(DRSU_DRC_ALARM_RPT_PERIOD_CFG_RSP,   0),
DECL_EVENT(DRSU_DRC_DATA_INFO_IND,              0),
/* 请在尾部（这里）追加，不要增删前面的枚举 */

