/************************************************************
  Copyright (C), BroadXt Inc  2019
  FileName: decl_errid.h
  Author: josephzhou    Version :  1.0   Date: 20190617
  Description:      This file defines all error id
    0x1000~0x3FFF   DRC&ACU error ID
    0x4000~0x7FFF   DRC&DRSU error ID
    0x8000~0xBFFF   DRC&CRM error ID

  Function List:    
    1. -------
  History:          
  <author>      <time>          <version >   <desc>
  josephzhou    2019/6/17         1.0        initial
***********************************************************/




/*-------------linux error infomation-------------*/
DECL_ERRID_BEGIN(RET_SUCCESS, 0),// 1

DECL_ERRID(ERRID_OS_OPERATION_NOT_PERMITTED),// 2
DECL_ERRID(ERRID_OS_NO_SUCH_FILE_OR_DIRECORY),// 3

/*-------------common error infomation-------------*/
DECL_ERRID_BEGIN(ERRID_DRC_COMMON_BEGIN, 8*ERRID_SEG_LEN),//2048
DECL_ERRID(ERRID_DR_OTHERS),//2049

/*-------------DRC&ACU error infomation-------------*/
DECL_ERRID_BEGIN(ERRID_DRC_ACU_BEGIN, 16*ERRID_SEG_LEN),//4096
DECL_ERRID(ERRID_DRC_ACU_DISPATCH_FAIL),//4097
DECL_ERRID(ERRID_DRC_ACU_OTHER),//4098
DECL_ERRID(ERRID_DRC_ACU_SW_IND_FAIL_CAN_NOT_GET_FILE),//4099
DECL_ERRID(ERRID_DRC_ACU_SW_IND_FAIL_FILE_ERROR),//4100
DECL_ERRID(ERRID_DRC_ACU_ILLEGAL_USER),//4101




/*-------------DRC&DRSU error infomation-------------*/
DECL_ERRID_BEGIN(ERRID_DRC_DRSU_BEGIN, 64*ERRID_SEG_LEN),//16384

//common from drc&crm
DECL_ERRID(ERRID_DRC_DRSU_KEY_PARA_MISSING),//16385
DECL_ERRID(ERRID_DRC_DRSU_PARTIAL_SUCCESS), //16386
DECL_ERRID(ERRID_DRC_DRSU_OTHER),//16387
DECL_ERRID(ERRID_DRC_DRSU_MSG_PARSE_FAIL),//16388

//register from crm to drsu
DECL_ERRID(ERRID_DRC_DRSU_ILLEGAL_USER),//16389
DECL_ERRID(ERRID_DRC_DRSU_REG_ERRPARA_MAC),//16390

//register from drc to drsu
DECL_ERRID(ERRID_DRC_DRSU_DRSU_REG_TIMEROUT), //16391
DECL_ERRID(ERRID_DRC_DRSU_DRSU_OVERLOAD), //16392
DECL_ERRID(ERRID_DRC_DRSU_DRSU_STATE_NOT_ALLOWED),//16393 
DECL_ERRID(ERRID_DRC_DRSU_DRSU_ALREDAY_REGISTER), //16394

//sw update from drsu&drc to crm
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_SAME_VERSION),//16395
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_DEVSTAT_NOT_ALLOWED),//16396
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_OLDER_RVERSION),//16397
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_SWFILE_ABNORMAL),//16398
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_FTP_EXPIRY),//16399         drsu delete
DECL_ERRID(ERRID_DRC_DRSU_SW_UPDATE_FTP_CANNOT_LOGIN),//16400   drsu delete
//others
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_UPDATE_FAIL),//16401            drsu delete
DECL_ERRID(ERRID_DRC_DRSU_MAP_UPDATE_MSG_ERR),   //16402        drsu delete
DECL_ERRID(ERRID_DRC_DRSU_POWER_EXEC_FAIL),//16403              drsu delete
DECL_ERRID(ERRID_DRC_DRSU_POWER_CONTROL_MSG_ERR),//16404        drsu delete
DECL_ERRID(ERRID_DRC_DRSU_POWER_CONTROL_NOT_SUPPORT),//16405    drsu delete
DECL_ERRID(ERRID_DRC_DRSU_DEVICE_POWER_MSG_ERR),//16406         drsu delete

//hdmap
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_SAME_VERSION),//16407
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_DEVSTAT_ABNORMAL),//16408
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_UPDATE_REPEAT),//16409
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_UPDATE_MSG_ERR), //16410
DECL_ERRID(ERRID_DRC_DRSU_HDMAP_FTP_EXPIRY), //16411            drsu delete

//power controller
DECL_ERRID(ERRID_DRC_DRSU_CFG_TEMP_THRESHOLD_FAIL),       //16412(0x401C), 
DECL_ERRID(ERRID_DRC_DRSU_CFG_BOX_OPEN_ALARM_TIME_FAIL),  //16413(0x401D), 
DECL_ERRID(ERRID_DRC_DRSU_CFG_BUS_OPERATION_TIME_FALT),   //16414(0x401E), 

//drsu hardware not support
DECL_ERRID(ERRID_DRSU_HADWARE_NOT_SUPPORT),    //16415(0x401F),  drsu delete
//whatever the feature, drsu software not support
DECL_ERRID(ERRID_DRSU_NOT_SUPPORT),            //16416(0x4020), 
DECL_ERRID(ERRID_PARA_PARSE_FAIL),    
DECL_ERRID(ERRID_PARA_RANGE_FAIL),  
DECL_ERRID(ERRID_TOTAL_OVER_LIMIT), 
DECL_ERRID(ERRID_REPEAT_EVENT),   
DECL_ERRID(ERRID_REPEAT_OPER),  
DECL_ERRID(ERRID_CFG_HANDLE_FAIL), 
DECL_ERRID(ERRID_CFG_HANDLE_TIMEOUT),
   

DECL_ERRID(ERRID_VIDEEO_PREVIEWING),  
DECL_ERRID(ERRID_NON_EXIST_VIDEEO_PREVIEW), 

DECL_ERRID(ERRID_DRC_DRSU_DELAY_REGISTER),

DECL_ERRID(ERRID_DRSU_INVALID_DEVICE),     
DECL_ERRID(ERRID_DRSU_FANS_TMPRT_CHECK_FAIL), 
DECL_ERRID(ERRID_DRSU_FANS_TMPRT_CFG_FAIL), 
DECL_ERRID(ERRID_DRSU_DISABLE_TIME_CHECK_FAIL),
DECL_ERRID(ERRID_DRSU_DISABLE_TIME_CFG_FAIL),
DECL_ERRID(ERRID_DRSU_DEVICE_POWEROFF_FAIL),
DECL_ERRID(ERRID_DRSU_DEVICE_POWERON_FAIL),
DECL_ERRID(ERRID_DRSU_TRAFFIC_WARNING_EVENT_NON_EXIST),
DECL_ERRID(ERRID_EQUIP_BOX_OPEN_ALARM_DISABLE_TIME_OVER_LIMIT), 

/*-------------DRC&CRM error infomation-------------*/
DECL_ERRID_BEGIN(ERRID_DRC_CRM_BEGIN, 128*ERRID_SEG_LEN),// 32768

////gloable
DECL_ERRID(ERRID_DRC_CRM_KEY_PARA_MISSING),//gloable 32769
DECL_ERRID(ERRID_DRC_CRM_PARTIAL_SUCCESS), //gloable 32770
DECL_ERRID(ERRID_DRC_CRM_OTHER),//gloable 32771
DECL_ERRID(ERRID_DRC_CRM_NO_DEVICE_ON_LINE),   //gloable 32772
DECL_ERRID(ERRID_DRC_CRM_DEVICE_OFF_LINE),  //gloable 32773

//register
DECL_ERRID(ERRID_DRC_CRM_DRC_INITREG_ILLEGAL_USER),//32774
DECL_ERRID(ERRID_DRC_CRM_DRC_INITREG_ERRPARA_SERVERMOD),//32775
DECL_ERRID(ERRID_DRC_CRM_DRC_INITREG_ERRPARA_OSVERSION),//32776
DECL_ERRID(ERRID_DRC_CRM_DRC_INITREG_OTHER),//32777


DECL_ERRID(ERRID_DRC_CRM_ACU_REG_ILLEGAL_USER),//32778
DECL_ERRID(ERRID_DRC_CRM_ACU_REG_ERRPARA_ENGINESERIALNUM),//32779
DECL_ERRID(ERRID_DRC_CRM_ACU_REG_ERRPARA_PLATENUMBER),//32780
DECL_ERRID(ERRID_DRC_CRM_ACU_REG_OTHER),//32781

DECL_ERRID(ERRID_DRC_CRM_DRSU_REG_ILLEGAL_USER),//32782
DECL_ERRID(ERRID_DRC_CRM_DRSU_REG_ERRPARA_MAC),//32783

DECL_ERRID(ERRID_DRC_CRM_ACU_REG_TIMEROUT),//32784

//config
DECL_ERRID(ERRID_DRC_CRM_ACU_CFG_TIME_OUT),//32785


//schedule
DECL_ERRID(ERRID_DRC_CRM_ACU_SCHEDULE_FAIL),//32786

//update DRC
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_RSP_SAME_VERSION ),  //save version  //32787
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_RSP_DEVSTAT_NOT_ALLOWED),//dev state is not suitable for upgrade //32788
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_RSP_OLDER_RVERSION),//drc has a newer version 32789
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_IND_SWFILE_ABNORMAL),//32790
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_IND_FTP_EXPIRY),//32791
DECL_ERRID(ERRID_DRC_CRM_DRC_SW_IND_FTP_CANNOT_LOGIN),//32792

//update MAP
DECL_ERRID(ERRID_DRC_CRM_MAP_UPDATE_EXPIRY),//32793

   

//ACU sw update 
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_SAME_VERSION),//32794
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_DEVSTAT_NOT_ALLOWED),//32795
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_OLDER_RVERSION),//32796
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_SWFILE_ABNORMAL),//32797
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_FTP_EXPIRY),//32798
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_UPDATE_FTP_CANNOT_LOGIN),//32799
DECL_ERRID(ERRID_DRC_CRM_ACU_SW_TIME_OUT),//32800



DECL_ERRID(ERRID_DRC_CRM_SUBDEV_POWER_EXPIRY),//32801
DECL_ERRID(ERRID_DRC_CRM_DRSU_POWER_EXPIRY),//32802

//log

DECL_ERRID(ERRID_DRC_CRM_DISPATCH_FAIL),//32803

//from drsu
DECL_ERRID(ERRID_DRC_CRM_HDMAP_UPDATE_FAIL),//32804

DECL_ERRID(ERRID_DRC_CRM_MAP_UPDATE_MSG_ERR),   ////todo delete 32805

DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_SAME_VERSION),//32806
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_DEVSTAT_NOT_ALLOWED),//32807
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_OLDER_RVERSION),//32808
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_SWFILE_ABNORMAL),//32809
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_FTP_EXPIRY),//32810
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_FTP_CANNOT_LOGIN),//32811
DECL_ERRID(ERRID_DRC_CRM_DRSU_SW_UPDATE_TIME_OUT), //has not receive IND message 32812

DECL_ERRID(ERRID_DRC_CRM_POWER_EXEC_FAIL),//32813
DECL_ERRID(ERRID_DRC_CRM_POWER_CONTROL_MSG_ERR),//32814
DECL_ERRID(ERRID_DRC_CRM_POWER_CONTROL_NOT_SUPPORT),//32815
DECL_ERRID(ERRID_DRC_CRM_DEVICE_POWER_MSG_ERR),//32816
DECL_ERRID(ERRID_DRC_CRM_BOX_OPEN_AUTO_ALARM_TIME_OUT),   //32817(0x8031), 
    
//release 2.1.0
DECL_ERRID(ERRID_DRC_CRM_ALL_FAIL), //gloable 32818(0x8032), 
DECL_ERRID(ERRID_DRC_CRM_TIME_OUT), //gloable 32819(0x8033), 


/*-------------DRC&DRSU alarm id-------------*/
DECL_ERRID_BEGIN(ERRID_DRC_DRSU_ALARM_BEGIN, 192*ERRID_SEG_LEN),//49152

/*-------------DRC&DRSU alarm id-------------*/
DECL_ERRID_BEGIN(ERRID_PLATFORM_BEGIN, 224*ERRID_SEG_LEN),//57344
DECL_ERRID(ERRID_FTP_LOGIN_CONNECT_FAIL),//57345
DECL_ERRID(ERRID_FTP_LOGIN_FDOPEN_FAIL),//57346
DECL_ERRID(ERRID_FTP_LOGIN_FTPCMD_FAIL),//57347
DECL_ERRID(ERRID_FTP_LOGIN_PASS_FAIL),//57348
DECL_ERRID(ERRID_FTP_LOGIN_USER_FAIL),//57349
DECL_ERRID(ERRID_FTP_LOGIN_TYPEI_FAIL),//57350
DECL_ERRID(ERRID_FTP_SEND_PASV_FAIL),//57351
DECL_ERRID(ERRID_FTP_SEND_FTPDATA_FAIL),//57352
DECL_ERRID(ERRID_FTP_SEND_XOPEN_FAIL),//57353
DECL_ERRID(ERRID_FTP_SEND_ALLO_FAIL),//57354
DECL_ERRID(ERRID_FTP_SEND_STOR_FAIL),//57355
DECL_ERRID(ERRID_FTP_SEND_BBEOF_FAIL),//57356
DECL_ERRID(ERRID_FTP_SEND_CLOSE_FAIL),//57357
DECL_ERRID(ERRID_FTP_CMD_FGETS_FAIL),//57358
DECL_ERRID(ERRID_FTP_RECIEVE_PASV_FAIL),//57359
DECL_ERRID(ERRID_FTP_RECIEVE_RETR_FAIL),//57360
DECL_ERRID(ERRID_FTP_RECIEVE_XOPEN_FAIL),//57361
DECL_ERRID(ERRID_FTP_RECIEVE_COPYFD_FAIL),//57362
DECL_ERRID(ERRID_FTP_RECIEVE_CLOSE_FAIL),//57363
DECL_ERRID(ERRID_FTP_SERVER_IP_INPUT_FAIL),//57364
DECL_ERRID(ERRID_FTP_LOCAL_FILE_OPEN_FAIL),//57365
DECL_ERRID(ERRID_FTP_CHECK_VERSION_BASE_FAIL),//57366
DECL_ERRID(ERRID_FTP_CHECK_VERSION_INFOLOG_FAIL),//57367
DECL_ERRID(ERRID_FTP_CHECK_VERSION_MD5_FAIL),//57368
DECL_ERRID(ERRID_FTP_CHECK_VERSION_STARTUP_FAIL),//57369
DECL_ERRID(ERRID_FTP_CHECK_VERSION_DEST_PATH_FAIL),//57370
DECL_ERRID(ERRID_FTP_CHECK_VERSION_SOURCE_PATH_FAIL),//57371



