/********************************************************************
  Copyright (C), broadxt Inc  2019
  FileName: decl_event_drc.h
  Author: josephzhou      Version : v0.1         Date:2019-5-24
  Description:     define message Identities
  History:     
  <author>       <time>         <version >      <desc>
  josephzhou     2019/05/24     v0.1            build this moudle 
  josephzhou     2019/06/13     v0.1            add DRC&DRSU, DRC&DRCRM message ID 
  josephzhou     2022/11/01     v0.2            add DRF message ID 
  note：only support three kinds of message: _REQ, _CFM, _IND, _RSP

        DRC<->ACU       0x0   ~0x3FF
        DRC<->DRSU      0x400 ~0x7FF
        DRC<->DRCRM     0x800 ~0xBFF
        DRC INTER       0x1000~0x3FFF
              
        DRSU<->DRC      0x4000~0x43FF
        DRSU INTER      0x5000~0x6FFF
        DRF INTER       0x6000~0x7FFF
              
        DRCRM<->DRC     0x8000~0x8FFF
        DRCRM INTER     0x9000~0xBFFF
        PLATFORM        0xFF00~0xFFFF
*******************************************************************/

/*----------DRSU内部交互消息定义---------*/
DECL_BEGIN(DRSU_INTER_BEGIN_MSG,         0, (EVENT_SEG_LEN*80)),//20480(0x5000)
//timer out type ID
DECL_EVENT(CTRL_MODULE_REG_TIMER_OUT,          0),//20481(0x5001)
DECL_EVENT(CTRL_DRSU_REG_TIMER_OUT,            0),//20483(0x5003)
DECL_EVENT(CTRL_HDM_UPDATE_TIMER_OUT,          0),//20484(0x5004)
DECL_EVENT(CTRL_DEVICE_REPORT_TIMEROUT,        0),//20485(0x5005)
DECL_EVENT(CTRL_SENSOR_POWER_TIMEROUT,         0),//20486(0x5006)
DECL_EVENT(CTRL_SENSOR_ALL_POWER_TIMEROUT,     0),//20487(0x5007)
DECL_EVENT(CTRL_MODULE_POWER_TIMEROUT,         0),//20488(0x5008)
DECL_EVENT(CTRL_MODULE_ALL_POWER_TIMEROUT,     0),//20489(0x5009)
DECL_EVENT(CTRL_WAIT_POWERON_TIMEROUT,         0),//20490(0x500A)
DECL_EVENT(CTRL_WAIT_ALL_POWERON_TIMEROUT,     0),//20491(0x500B)

//pf
DECL_EVENT(PF_CTRL_BREAK_CHAIN_REPORT,      0),
DECL_EVENT(PF_CTRL_MODULE_CFG_TIMEROUT,     0),
DECL_EVENT(PF_CTRL_ALARM_REPORT_TIMEOUT,    0),
DECL_EVENT(PF_CTRL_AUTO_POWER_TIMEOUT,      0),
DECL_EVENT(PF_CTRL_SINGLE_STATUS_REPORT_TIMEOUT,    0),
DECL_EVENT(PF_CTRL_ALL_STATUS_REPORT_TIMEOUT,    0),
DECL_EVENT(PF_CTRL_WAIT_MONITDP_RSP_TIMEOUT,    0),
DECL_EVENT(PF_CTRL_EQUIT_BOX_TMPRT_TIMEOUT,    0),


DECL_EVENT(MODULE_ALARM_REPORT_NOTIFY,         0),//20493(0x500D)

//rsp for module register 
DECL_EVENT(CTRL_MODULE_REG_RSP,                0),//20494(0x500E)
DECL_EVENT(CTRL_MODULE_REG_RSP_TIMEOUT,        0),//20495(0x500F)

//alarm
DECL_EVENT(MODULE_CTRL_ALARM_NOTIFY,           0),//20496(0x5010)

//AI data
DECL_EVENT(AIDATA_CTRL_REG_IND, 0),
DECL_EVENT(CTRL_AIDATA_CFG_REQ, 0),
DECL_EVENT(AIDATA_CTRL_CFG_RSP, 0),
DECL_EVENT(AI_DS_DATA_NOTIFY, 0),

//CAMERA ADAPTER
DECL_EVENT(CAMERAADAPTER_CTRL_REG_IND, 0),
DECL_EVENT(CTRL_CAMERAADAPTER_CFG_REQ, 0),
DECL_EVENT(CAMERAADAPTER_CTRL_CFG_RSP, 0),
DECL_EVENT(AIDATA_CAMERAADAPTER_PIC_DATA, 0),
DECL_EVENT(CAMERAADAPTER_AIDATA_ADJUST_RESULT, 0),

//AI ctrl
DECL_EVENT(AICTRL_CTRL_REG_IND, 0),
DECL_EVENT(CTRL_AICTRL_CFG_REQ, 0),
DECL_EVENT(AICTRL_CTRL_CFG_RSP, 0),
DECL_EVENT(CTRL_AICTRL_ROAD_SURFACE_CFG_REQ, 0),
DECL_EVENT(AICTRL_CTRL_ROAD_SURFACE_CFG_RSP, 0),

//DM
DECL_EVENT(DM_CTRL_REG_IND,             0),//20501(0x5015)
DECL_EVENT(CTRL_DM_CFG_REQ,             0),//20502(0x5016)
DECL_EVENT(DM_CTRL_CFG_RSP,             0),//20503(0x5017)
DECL_EVENT(CTRL_DM_DEVICE_POWEROFF_REQ,           0),//20504(0x5018)
DECL_EVENT(DM_CTRL_DEVICE_POWEROFF_RSP,           0),//20505(0x5019)
DECL_EVENT(CTRL_DM_DEVICE_POWERON_REQ,         0),//20506(0x501A)
DECL_EVENT(DM_CTRL_DEVICE_POWERON_RSP,         0),//20507(0x501B)
DECL_EVENT(CTRL_DM_ALL_SENSOR_POWEROFF_REQ,   0),//20508(0x501C)
DECL_EVENT(DM_CTRL_ALL_SENSOR_POWEROFF_RSP,            0),//20509(0x501D)
DECL_EVENT(CTRL_DM_ALL_SENSOR_POWERON_REQ,             0),//20510(0x501E)
DECL_EVENT(DM_CTRL_ALL_SENSOR_POWERON_RSP,             0),//20510(0x501E)
DECL_EVENT(CTRL_DM_FANS_TMPRT_CFG_REQ,               0),//20511(0x501F)
DECL_EVENT(DM_CTRL_FANS_TMPRT_CFG_RSP,           0),//20512(0x5020)
DECL_EVENT(CTRL_DM_EQUIP_BOX_OPEN_ALARM_DISABLE_TIME_CFG_REQ,               0),//20511(0x501F)
DECL_EVENT(DM_CTRL_EQUIT_BOX_OPEN_ALARM_DISABLE_TIME_CFG_RSP,           0),//20512(0x5020)
DECL_EVENT(DM_CTRL_EQUIT_BOX_TMPRT_REPORT_IND,           0),//20512(0x5020)
DECL_EVENT(DM_CTRL_BOX_DOOR_STATUS_REPORT_IND,           0),//20512(0x5020)
DECL_EVENT(DM_CTRL_CHANGE_POWERON_REPORT_IND,           0),//20512(0x5020)
DECL_EVENT(DM_CTRL_CHANGE_POWEROFF_REPORT_IND,           0),//20512(0x5020)


//LiDar
DECL_EVENT(LIDARDP_CTRL_REG_IND,               0),//20513(0x5021)
DECL_EVENT(CTRL_LIDARDP_CFG_REQ,               0),//20516(0x5024)
DECL_EVENT(LIDARDP_CTRL_CFG_RSP,           0),//20518(0x5026)
DECL_EVENT(CTRL_LIDARDP_POWERON_REQ,         0),//20519(0x5027)
DECL_EVENT(LIDARDP_CTRL_POWERON_RSP,         0),//20520(0x5028)
DECL_EVENT(CTRL_LIDARDP_POWEROFF_IND,         0),//20520(0x5028)
DECL_EVENT(LIDARDP_CTRL_ALARM_NOTIFY,          0),//请使用 MODULE_ALARM_REPORT_NOTIFY 20522(0x502A)
DECL_EVENT(LIDAR_LIDARDP_DATA_NOTIFY,       0),
DECL_EVENT(PF_LIDARDP_FAST_CHECK_STATUS_TIMEOUT,      0),
DECL_EVENT(PF_LIDARDP_FIRST_FRAME_NOT_RECV_TIMEOUT,      0),
DECL_EVENT(PF_LIDARDP_RECONN_LIDAR_TIMEOUT,      0),
DECL_EVENT(PF_LIDARDP_CHECK_LIDAR_DATA_STATUS_TIMEOUT,      0),
DECL_EVENT(LIDARDP_CTRL_STATUS_CHANGE_REPORT_IND,      0),
DECL_EVENT(CTRL_LIDARDP_DATASYNC_IND,      0),
DECL_EVENT(LIDARDP_CTRL_SENSOR_DATA_SYNC_RSP,      0),
DECL_EVENT(LIDARDP_CTRL_RECONN_OVER_MAX_COUNT_IND, 0),
DECL_EVENT(LIDARDP_CTRL_CHANGE_REPORT_IND, 0),
DECL_EVENT(LIDARDP_AIDATA_DATA_NOTIFY, 0),

//Camera
DECL_EVENT(CAMERADP_CTRL_REG_IND,          0),//20525(0x502D)
DECL_EVENT(CAMERADP_VA_HANDSHAKE,    0),
DECL_EVENT(CTRL_CAMERADP_DATASYNC_IND,    0),
DECL_EVENT(CAMERADP_CTRL_DATA_SYNC_RSP,    0),
DECL_EVENT(CAMERADP_CTRL_FRAME_RETE_ALARM_IND,    0),
DECL_EVENT(PF_CAMERADP_FRAME_RATE_CHECK_TIMEOUT,    0),
DECL_EVENT(PF_CAMERADP_DATA_NOTIFY,    0),
DECL_EVENT(CAMERADP_CTRL_STATUS_CHANGE_REPORT_IND,      0),
DECL_EVENT(CAMERADP_AIDATA_DATA_NOTIFY, 0),

DECL_EVENT(CTRL_CAMERADP_REG_RSP,          0),//请使用 CTRL_MODULE_REG_RSP 20526(0x502E)
DECL_EVENT(CTRL_CAMERADP_REG_RSP_TIMEOUT,  0),//20527(0x502F)
DECL_EVENT(CTRL_CAMERADP_CFG_REQ,          0),//20528(0x5030)
DECL_EVENT(CAMERADP_WAIT_CTRL_CFG_TIMEOUT, 0),//20529(0x5031)
DECL_EVENT(CAMERADP_CTRL_CFG_RSP,          0),//20530(0x5032)
DECL_EVENT(CTRL_CAMERADP_POWER_REQ,        0),//20531(0x5033)
DECL_EVENT(CAMERADP_CTRL_POWER_RSP,        0),//20532(0x5034)
DECL_EVENT(CAMERADP_CTRL_ALARM_NOTIFY,          0),//请使用 MODULE_ALARM_REPORT_NOTIFY 20534(0x5036)
DECL_EVENT(CAMERADP_AI_DATA_NOTIFY,             0),//20535(0x5037)
DECL_EVENT(CAMERADP_DS_RAWDATA_NOTIFY,          0),//20536(0x5038)
DECL_EVENT(CTRL_CAMERADP_DEVICE_STATUS_REQ,     0),//20537(0x5039)
DECL_EVENT(CAMERADP_CTRL_RECONN_OVER_MAX_COUNT_IND, 0),
DECL_EVENT(CAMERADP_CTRL_CHANGE_REPORT_IND, 0),
DECL_EVENT(CTRL_CAMERADP_POWERON_REQ,     0),
DECL_EVENT(CAMERADP_CTRL_POWERON_RSP,     0),
DECL_EVENT(CTRL_CAMERADP_POWEROFF_IND,     0),
DECL_EVENT(PF_CAMERADP_FAST_CHECK_STATUS_TIMEOUT,     0),
DECL_EVENT(PF_CAMERADP_CHECK_CAMERA_DATA_STATUS_TIMEOUT,     0),
DECL_EVENT(PF_CAMERADP_DISCONN_NOTIFY,     0),

//DS
DECL_EVENT(DS_CTRL_REG_IND,                 0),
DECL_EVENT(CTRL_DS_CFG_REQ,                 0),
DECL_EVENT(DS_CTRL_CFG_RSP,                 0),
DECL_EVENT(PF_DS_RECONN_TIMEROUT,           0),
DECL_EVENT(PF_DS_BREAK_CHAIN_IND,           0),
DECL_EVENT(PF_DS_FRAME_RATE_CHECK_TIMEOUT,    0),
DECL_EVENT(DS_CTRL_FRAME_RETE_ALARM_IND,    0),



//monitdp
DECL_EVENT(MONITDP_CTRL_REG_IND,                          0),
DECL_EVENT(CTRL_MONITDP_CFG_REQ,                          0),
DECL_EVENT(MONITDP_CTRL_CFG_RSP,                          0),
DECL_EVENT(CTRL_MONITDP_START_VIDEO_REQ,                  0),
DECL_EVENT(MONITDP_CTRL_START_VIDEO_RSP,                  0),
DECL_EVENT(CTRL_MONITDP_IDLE_START_VIDEO_REQ,             0),
DECL_EVENT(MONITDP_CTRL_IDLE_START_VIDEO_RSP,             0),
DECL_EVENT(CTRL_MONITDP_UPDATE_VIDEO_REQ,                 0),
DECL_EVENT(MONITDP_CTRL_UPDATE_VIDEO_RSP,                 0),
DECL_EVENT(CTRL_MONITDP_STOP_VIDEO_REQ,                   0),
DECL_EVENT(MONITDP_CTRL_STOP_VIDEO_RSP,                   0),
DECL_EVENT(CTRL_MONITDP_VIDEO_PTZ_CTRL_REQ,               0),
DECL_EVENT(MONITDP_CTRL_VIDEO_PTZ_CTRL_RSP,               0),
DECL_EVENT(CTRL_MONITDP_VIDEO_REPORT_REQ,                 0),
DECL_EVENT(MONITDP_CTRL_VIDEO_REPORT_RSP,                 0),
DECL_EVENT(CTRL_MONITDP_MODIFY_VIDEO_DEFINITION_REQ,      0),
DECL_EVENT(MONITDP_CTRL_MODIFY_VIDEO_DEFINITION_RSP,      0),
DECL_EVENT(MONITDP_CTRL_CAMERA_STATUS_CHANGE_REPORT_IND,  0),
DECL_EVENT(PF_MONITDP_CYCLE_RECV_CAMERA_KEEPALIVE_TIMEOUT,0),
DECL_EVENT(PF_MONITDP_WAIT_IPC_REGISTER_TIMEOUT,          0),
DECL_EVENT(MONITDP_CTRL_IPC_STATE_ALARM_IND,    0),


/* sensor module is created by lidar driver */
DECL_EVENT(SENSOR_LIDARDP_DATA_NOTIFY,     0),//20549(0x5045)


DECL_EVENT(CTRL_SOFT_UPDATE_TIMER_OUT,         0),//20551(0x5047)
DECL_EVENT(CTRL_DS_DATA_CHAIN_NOTIFY_REQ,      0),//20552(0x5048)
DECL_EVENT(CTRL_DS_DATA_CHAIN_NOTIFY_RSP,      0),//20553(0x5049)
DECL_EVENT(CTRL_LIDARDP_DEVICE_STATUS_REQ,     0),//20554(0x504A)

DECL_EVENT(DS_NET_SESSION_TIMEROUT,            0),//20555(0x504B)
DECL_EVENT(DS_BREAK_CHAIN_REPORT,              0),//20556(0x504C)

DECL_EVENT(CTRL_NET_SESSION_TIMEROUT,          0),//20557(0x504D)
DECL_EVENT(CTRL_NOTIFY_DS_OBSTACLE_TIMEROUT,   0),//20558(0x504E)

//breakchain
DECL_EVENT(CTRL_BREAK_CHAIN_REPORT,            0),//20560(0x5050)

DECL_EVENT(DM_VA_HANDSHAKE,                    0),//20561(0x5051)
DECL_EVENT(DM_SENSOR_CONN_TIMEOUT,             0),//20562(0x5052)
DECL_EVENT(DM_CTRL_DYNAMIC_REPORT_REQ,         0),//20563(0x5053)
DECL_EVENT(CTRL_DM_DYNAMIC_REPORT_RSP,         0),//20564(0x5054)

DECL_EVENT(CTRL_WAIT_DS_CHAIN_STATE_OPER_TIMEROUT,     0),//20565(0x5055)
DECL_EVENT(CTRL_RELOAD_RUNTIME_CONFIG_TIMEROUT,        0),//20566(0x5056)
DECL_EVENT(CTRL_WAIT_CFG_POWER_CTRL_TIMEOUT,           0),//20567(0x5057)
DECL_EVENT(CTRL_GET_CURRENT_TIME_TIMEOUT,              0),//20568(0x5058)

//DM AND POWER CONTROLLER
DECL_EVENT(PF_DM_POWER_CTRL_RSP_TIMEOUT,         0),//20576(0x5060)
DECL_EVENT(PF_DM_CYCLE_QUERY_POWER_CTRL_TIMEOUT,              0),//20582(0x5066)

//cameraDrv
DECL_EVENT(CAMERADRV_CTRL_REG_IND, 0),
DECL_EVENT(CTRL_CAMERADRV_CFG_REQ, 0),
DECL_EVENT(CAMERADRV_CTRL_CFG_RSP, 0),
DECL_EVENT(CAMERADRV_CTRL_FRAME_RETE_ALARM_IND,    0),
DECL_EVENT(CTRL_CAMERADRV_DATASYNC_IND, 0),
//DECL_EVENT(CAMERADRV_CTRL_SENSOR_DATA_SYNC_RSP, 0),
DECL_EVENT(PF_CAMERADRV_GET_DATA_TIMEOUT, 0),
DECL_EVENT(PF_CAMERADRV_FRAME_RATE_CHECK_TIMEOUT,    0),
DECL_EVENT(CAMERADRV_CAMERADP_DATA_NOTIFY, 0),
DECL_EVENT(CAMERADRV_GET_CAMERADATA_IND, 0),
DECL_EVENT(CAMERADRV_CAMERAENC_DATA_NOTIFY, 0),
DECL_EVENT(CAMERADRV_AIDATA_DATA_NOTIFY, 0),

DECL_EVENT(PF_DM_POWER_CTRL_MSG_RSP,         0),//20576(0x5060)

//radardp
DECL_EVENT(RADARDP_CTRL_REG_IND,          0),

DECL_EVENT(PF_RADARDP_RECONN_CAMERA_TIMEOUT,    0),
DECL_EVENT(PF_RADARDP_FIRST_FRAME_NOT_RECV_TIMEOUT,    0),
DECL_EVENT(RADARDP_CTRL_STATUS_CHANGE_REPORT_IND,      0),
DECL_EVENT(RADARDP_AIDATA_DATA_NOTIFY, 0),

DECL_EVENT(CTRL_RADARDP_REG_RSP,          0),
DECL_EVENT(CTRL_RADARDP_REG_RSP_TIMEOUT,  0),
DECL_EVENT(CTRL_RADARDP_CFG_REQ,          0),
DECL_EVENT(RADARDP_WAIT_CTRL_CFG_TIMEOUT, 0),
DECL_EVENT(RADARDP_CTRL_CFG_RSP,          0),
DECL_EVENT(CTRL_RADARDP_POWER_REQ,        0),
DECL_EVENT(RADARDP_CTRL_POWER_RSP,        0),
DECL_EVENT(RADARDP_CTRL_ALARM_NOTIFY,          0),
DECL_EVENT(RADARDP_AI_DATA_NOTIFY,             0),
DECL_EVENT(RADARDP_DS_RAWDATA_NOTIFY,          0),
DECL_EVENT(CTRL_RADARDP_DEVICE_STATUS_REQ,     0),
DECL_EVENT(RADARDP_CTRL_RECONN_OVER_MAX_COUNT_IND, 0),
DECL_EVENT(RADARDP_CTRL_CHANGE_REPORT_IND, 0),
DECL_EVENT(CTRL_RADARDP_POWERON_REQ,     0),
DECL_EVENT(RADARDP_CTRL_POWERON_RSP,     0),
DECL_EVENT(CTRL_RADARDP_POWEROFF_IND,     0),
DECL_EVENT(PF_RADARDP_FAST_CHECK_STATUS_TIMEOUT,     0),
DECL_EVENT(PF_RADARDP_CHECK_RADAR_DATA_STATUS_TIMEOUT,     0),
DECL_EVENT(PF_RADARDP_RECONN_RADAR_TIMEOUT,     0),

//radarDrv
DECL_EVENT(RADARDRV_CTRL_REG_IND, 0),
DECL_EVENT(CTRL_RADARDRV_CFG_REQ, 0),
DECL_EVENT(RADARDRV_CTRL_CFG_RSP, 0),
DECL_EVENT(PF_RADARDRV_FRAME_RATE_CHECK_TIMEOUT,    0),
DECL_EVENT(RADARDRV_CTRL_FRAME_RETE_ALARM_IND,    0),
DECL_EVENT(CTRL_RADARDRV_DATASYNC_IND, 0),
DECL_EVENT(RADARDRV_CTRL_SENSOR_DATA_SYNC_RSP, 0),
DECL_EVENT(RADARDRV_RADARDP_DATA_NOTIFY, 0),
DECL_EVENT(RADARDP_RADARDRV_RECONN_IND, 0),
DECL_EVENT(RADARDRV_RADARENC_DATA_NOTIFY, 0),
DECL_EVENT(RADARDRV_AIDATA_DATA_NOTIFY, 0),


//upload
DECL_EVENT(UPLOAD_CTRL_REG_IND,   0),
DECL_EVENT(CTRL_UPLOAD_CFG_REQ,   0),
DECL_EVENT(UPLOAD_CTRL_CFG_RSP,   0),
DECL_EVENT(CAMERAENC_UPLOAD_FILE_UPLOAD_IND,   0),
DECL_EVENT(RADARENC_UPLOAD_FILE_UPLOAD_IND,   0),
DECL_EVENT(PF_UPLOAD_CYCLE_CHECK_FILE_TIMEOUT,0),

//cameraenc
DECL_EVENT(CAMERAENC_CTRL_REG_IND,   0),
DECL_EVENT(CAMERAENC_CTRL_CFG_RSP,   0),
DECL_EVENT(CTRL_CAMERAENC_CFG_REQ,   0),

//radarenc
DECL_EVENT(RADARENC_CTRL_REG_IND,   0),
DECL_EVENT(CTRL_RADARENC_CFG_REQ,   0),
DECL_EVENT(RADARENC_CTRL_CFG_RSP,   0),

//download
DECL_EVENT(DOWNLOAD_CTRL_REG_IND,   0),
DECL_EVENT(CTRL_DOWNLOAD_CFG_REQ,   0),
DECL_EVENT(DOWNLOAD_CTRL_CFG_RSP,   0),
DECL_EVENT(DOWNLOAD_CAMERADEC_DECODE_REQ,   0),
DECL_EVENT(CAMERADEC_DOWNLOAD_DECODE_RSP,   0),
DECL_EVENT(DOWNLOAD_RADARDEC_DECODE_REQ,   0),
DECL_EVENT(RADARDEC_DOWNLOAD_DECODE_RSP,   0),
DECL_EVENT(PF_DOWNLOAD_MID_DECODE_RSP_TIMEOUT,   0),
DECL_EVENT(PF_DOWNLOAD_LONG_DECODE_RSP_TIMEOUT,   0),
DECL_EVENT(PF_DOWNLOAD_RADAR_DECODE_RSP_TIMEOUT,   0),
DECL_EVENT(CTRL_DOWNLOAD_DATASYNC_IND, 0),

//cameradec
DECL_EVENT(CAMERADEC_CTRL_REG_IND,   0),
DECL_EVENT(CTRL_CAMERADEC_CFG_REQ,   0),
DECL_EVENT(CAMERADEC_CTRL_CFG_RSP,   0),
DECL_EVENT(CAMERADEC_AIDATA_DATA_NOTIFY,   0),
DECL_EVENT(PF_CAMERADEC_GET_CAMERA_DATA_TIMEOUT,   0),
DECL_EVENT(CAMERADEC_RADARDEC_DATA_NOTIFY,   0),
DECL_EVENT(CAMERADEC_CAMERADEC_DATA_SYNC_NOTIFY,   0),
DECL_EVENT(CAMERADEC_CAMERADEC_VIDEO_DEC_SUCC, 0),
DECL_EVENT(PF_CAMERADEC_SEND_CAMERA_DATA_TIMEOUT,   0),

//radardec
DECL_EVENT(RADARDEC_CTRL_REG_IND,   0),
DECL_EVENT(CTRL_RADARDEC_CFG_REQ,   0),
DECL_EVENT(RADARDEC_CTRL_CFG_RSP,   0),
DECL_EVENT(RADARDEC_AIDATA_DATA_NOTIFY, 0),
DECL_EVENT(PF_RDARDEC_SEND_DATA_TIMEOUT,   0),

//drsu中的common模块注册信息
DECL_EVENT(DRSU_COMMON_REG_IND, 0),

//CTRL
DECL_EVENT(CTRL_UNINIT_IND,   0),

