/********************************************************************
  Copyright (C), broadxt Inc  2019
  FileName: decl_event_drc.h
  Author: josephzhou      Version : v0.1         Date:2019-5-24
  Description:     define message Identities
  History:
  <author>       <time>         <version >      <desc>
  josephzhou     2019/05/24     v0.1            build this moudle
  josephzhou     2019/06/13     v0.1            add DRC&DRSU, DRC&DRCRM message ID
  liyafei        2020/06/13     v0.1            add video related:4278~4282
  note：only support three kinds of message: _REQ, _CFM, _IND, _RSP

        DRC<->ACU       0x0   ~0x3FF
        DRC<->DRSU      0x400 ~0x7FF
        DRC<->DRCRM     0x800 ~0xBFF
        DRC INTER       0x1000~0x3FFF

        DRSU<->DRC      0x4000~0x43FF
        DRSU INTER      0x5000~0x7FFF

        DRCRM<->DRC     0x8000~0x8FFF
        DRCRM INTER     0x9000~0xBFFF
        PLATFORM        0xFF00~0xFFFF
*******************************************************************/



/*----------DRC内部交互消息定义---------*/
DECL_BEGIN(DRC_INTER_BEGIN_MSG,        0, (EVENT_SEG_LEN*16)),//4096(0x1000)
DECL_EVENT(CLUSTER_NODE_REGIST_REQ,          0),
DECL_EVENT(CLUSTER_NODE_REGIST_RSP,          0),
DECL_EVENT(DEVICE_KEEP_ALIVE_IND,            0),
DECL_EVENT(DEVICE_NODE_AWAKEN_IND,           0),
DECL_EVENT(DCSM_OAM_NEW_DRSU_REQ,           0),//4103(0x1007)  //use
DECL_EVENT(OAM_DCSM_NEW_DRSU_RSP,           0),//4104(0x1008)  //use
DECL_EVENT(DCSM_OAM_DRSU_DEVICE_INFO_IND,   0),//4105(0x1009)  //use
DECL_EVENT(OAM_DCSM_ALLDRSU_PARA_CFG_REQ,   0),//4106(0x100A)  //use
DECL_EVENT(DCSM_OAM_ALLDRSU_PARA_CFG_RSP,   0),//4107(0x100B)  //use
DECL_EVENT(OAM_DCSM_DEDIDRSU_PARA_CFG_REQ,  0),//4108(0x100C)  //use
DECL_EVENT(DCSM_OAM_DEDIDRSU_PARA_CFG_RSP,  0),//4109(0x100D)  //use
DECL_EVENT(OAM_DCSM_MAP_UPDATE_REQ,         0),//4110(0x100E)//use
DECL_EVENT(DCSM_OAM_MAP_UPDATE_RSP,         0),//4111(0x100F)//use
DECL_EVENT(DCSM_OAM_MAP_UPDATE_IND,         0),//4112(0x1010)//use
DECL_EVENT(OAM_DCSM_DRSU_SWUPDATE_REQ,      0),//4113(0x1011)//use
DECL_EVENT(DCSM_OAM_DRSU_SWUPDATE_RSP,      0),//4114(0x1012)//use
DECL_EVENT(DCSM_OAM_DRSU_SWUPDATE_IND,      0),//4115(0x1013)//use
DECL_EVENT(OAM_DCSM_DEDIDRSU_SWUPDATE_REQ,  0),//4116(0x1014)//use
DECL_EVENT(DCSM_OAM_DEDIDRSU_SWUPDATE_RSP,  0),//4117(0x1015)//use
DECL_EVENT(DCSM_OAM_DEDIDRSU_SWUPDATE_IND,  0),//4118(0x1016)//use
DECL_EVENT(DCSM_OAM_DRSU_ALARM_IND,         0),//4119(0x1017)
DECL_EVENT(OAM_DCSM_DRSU_ALARM_CFM,         0),//4120(0x1018)
DECL_EVENT(DCSM_OAM_DRSU_ALARM_CANCEL_IND,              0),//4121(0x1019)
DECL_EVENT(OAM_DCSM_DRSU_ALARM_CANCEL_CFM,              0),//4122(0x101A)
DECL_EVENT(OAM_DCSM_DEDIDRSU_SUBDEV_POWCTRL_REQ,        0),//4123(0x101B)
DECL_EVENT(DCSM_OAM_DEDIDRSU_SUBDEV_POWCTRL_RSP,        0),//4124(0x101C)
DECL_EVENT(OAM_DCSM_ALLDRSU_SUBDEV_POWCTRL_REQ,         0),//4125(0x101D)
DECL_EVENT(DCSM_OAM_ALLDRSU_SUBDEV_POWCTRL_RSP,         0),//4126(0x101E)
DECL_EVENT(OAM_DCSM_DRSU_ALLSUBDEV_POWCTRL_REQ,         0),//4125(0x101D)
DECL_EVENT(DCSM_OAM_DRSU_ALLSUBDEV_POWCTRL_RSP,         0),//4126(0x101E)
DECL_EVENT(OAM_DCSM_ALLDRSU_FANS_AUTO_TEMP_REQ,         0),//4127(0x101F)
DECL_EVENT(DCSM_OAM_ALLDRSU_FANS_AUTO_TEMP_RSP,         0),//4128(0x1020)
DECL_EVENT(OAM_DCSM_DEDIDRSU_BOX_OPEN_AUTO_ALARM_REQ,   0),//4129(0x1021)
DECL_EVENT(DCSM_OAM_DEDIDRSU_BOX_OPEN_AUTO_ALARM_RSP,   0),//4130(0x1022)
DECL_EVENT(DCSM_OAM_DEDIDRSU_EQUIP_BOX_STATUS_IND,      0),//4131(0x1023)
DECL_EVENT(OAM_DCSM_ALLDRSU_BUS_OPERATION_TIME_REQ,     0),//4132(0x1024)
DECL_EVENT(DCSM_OAM_ALLDRSU_BUS_OPERATION_TIME_RSP,     0),//4133(0x1025)
DECL_EVENT(OAM_DCSM_DRSU_RESTART_REQ,        	        0),//4134(0x1026)
DECL_EVENT(DCSM_OAM_DRSU_RESTART_RSP,                   0),//4134(0x1026)
DECL_EVENT(DCSM_OAM_DRSU_OFF_IND,                       0),//4136(0x1028)
DECL_EVENT(OAM_DCSM_DRC_REGISTER_IND,                   0),//4137(0x1029)
DECL_EVENT(OAM_DCSM_LOG_PARA_CFG_CMD,                   0),//4138(0x102A)
DECL_EVENT(OAM_DCSM_LOG_SWITCH_CTRL_CMD,                0),//4139(0x102B)
DECL_EVENT(DCSM_OAM_LOG_UPLOAD_IND,                     0),//4140(0x102C)
//DECL_EVENT(OAM_DCSM_INIT_CFG_REQ,                     0),
DECL_EVENT(OAM_DCSM_ALLDRSU_LOG_LEVEL_CFG_REQ,         0),//4204(0x106C)
DECL_EVENT(OAM_DCSM_DEDIDRSU_LOG_LEVEL_CFG_REQ,        0),//4205(0x106D)
DECL_EVENT(OAM_DCSM_DEDIDRSU_LOG_LEVEL_QUERY_REQ,      0),//4206(0x106E)
DECL_EVENT(DCSM_OAM_ALLDRSU_LOG_LEVEL_CFG_RSP,         0),//4207(0x106F)
DECL_EVENT(DCSM_OAM_DEDIDRSU_LOG_LEVEL_CFG_RSP,        0),//4208(0x1070)
DECL_EVENT(DCSM_OAM_DEDIDRSU_LOG_LEVEL_QUERY_RSP,      0),//4209(0x1071)
DECL_EVENT(DCSM_OAM_FAIL_IND,               0),//4210(0x1072)
DECL_EVENT(ACSM_OAM_FAIL_IND,               0),//4211(0x1073)
DECL_EVENT(OAM_DCSM_START_REAL_PLAY_VIDEO_REQ, 0),//4212(0x1074)
DECL_EVENT(DCSM_OAM_START_REAL_PLAY_VIDEO_RSP, 0),//4213(0x1075)
DECL_EVENT(OAM_DCSM_STOP_REAL_PLAY_VIDEO_REQ, 0),//4214(0x1076)
DECL_EVENT(DCSM_OAM_STOP_REAL_PLAY_VIDEO_RSP, 0),//4215(0x1077)
DECL_EVENT(OAM_DCSM_REPLAY_VIDEO_REQ, 0),//4216(0x1078)
DECL_EVENT(DCSM_OAM_REPLAY_VIDEO_RSP, 0),//4217(0x1079)
DECL_EVENT(OAM_DCSM_VIDEO_PLATFORM_CTRL_REQ, 0),//4218(0x108A)
DECL_EVENT(DCSM_OAM_VIDEO_PLATFORM_CTRL_RSP, 0),//4219(0x108B)
//DECL_EVENT(DCSM_OAM_CAMERA_DISK_STATUS_IND, 0),//4220(0x108C)
DECL_EVENT(OAM_DCSM_AI_CFG_REQ, 0),//4221(0x108D)
DECL_EVENT(DCSM_OAM_AI_CFG_RSP, 0),//4222(0x108E)
DECL_EVENT(OAM_DCSM_DEBUGFILE_UPLOAD_IMMEDIATELY_REQ,               0),//4239(0x109F)
DECL_EVENT(DCSM_OAM_DEBUGFILE_UPLOAD_IMMEDIATELY_RSP,               0),//4240(0x10A0)
DECL_EVENT(DCSM_OAM_SINGLE_SUBDEV_STATUS_RPT_IND,               0),
DECL_EVENT(DCSM_OAM_ALL_DEV_STATUS_IND,               0),
DECL_EVENT(DCSM_OAM_DRSU_ALLSUBDEV_POWCTRL_FAIL_IND,   0),
DECL_EVENT(OAM_RCII_TWOD_ALLDRSU_OBSTACLE_RPT_REQ,      0),//4141(0x102D)
DECL_EVENT(RCII_OAM_TWOD_ALLDRSU_OBSTACLE_RPT_RSP,      0),//4142(0x102E)
DECL_EVENT(OAM_RCII_TWOD_DEDIDRSU_OBSTACLE_RPT_REQ,     0),//4143(0x102F)
DECL_EVENT(RCII_OAM_TWOD_DEDIDRSU_OBSTACLE_RPT_RSP,     0),//4144(0x1030)
DECL_EVENT(OAM_RCII_THREED_DEDIDRSU_OBSTACLE_RPT_REQ,   0),//4145(0x1031)
DECL_EVENT(RCII_OAM_THREED_DEDIDRSU_OBSTACLE_RPT_RSP,   0),//4146(0x1032)
DECL_EVENT(RCII_OAM_TWOD_ALLDRSU_OBSTACLE_RPT_IND,      0),//4147(0x1033)
DECL_EVENT(RCII_OAM_TWOD_DEDIDRSU_OBSTACLE_RPT_IND,     0),//4148(0x1034)
DECL_EVENT(RCII_OAM_THREED_DEDIDRSU_OBSTACLE_RPT_IND,   0),//4149(0x1035)
DECL_EVENT(OAM_RCII_THREED_ALLDRSU_OBSTACLE_RPT_CMD,    0),//4150(0x1036)
DECL_EVENT(NETWORK_DCSM_DRSU_CP_DATA_IND,      	0),//4151(0x1037)
DECL_EVENT(NETWORK_RCII_DRSU_UP_DATA_IND,       0),//4152(0x1038)
DECL_EVENT(NETWORK_RCII_DRSU_UP_CONNECT_IND,    0),//4153(0x1039)
DECL_EVENT(NETWORK_DCSM_DRSU_CP_RELEASE_IND,    0),//4154(0x103A)
DECL_EVENT(NETWORK_RCII_DRSU_UP_RELEASE_IND,    0),//4155(0x103B)
DECL_EVENT(DCSM_RCII_NEW_DRSU_CFG_REQ,          0),//4156(0x103C)
DECL_EVENT(RCII_DCSM_NEW_DRSU_CFG_RSP,          0),//4157(0x103D)
DECL_EVENT(DCSM_RCII_DELETE_DRSU_IND,           0),//4158(0x103E)
DECL_EVENT(RCII_DCSM_DELETE_DRSU_RSP,           0),//4159(0x103F)//DELETE
DECL_EVENT(RCII_DCSM_DELETE_DRSU_IND,           0),//4160(0x1040)
DECL_EVENT(RCII_DCSM_DRSU_NEED_SYNC_IND,        0),//4161(0x1041)
DECL_EVENT(NET_OAM_DATA_IND,                    0),//4162(0x1042)
DECL_EVENT(NET_ACSM_DATA_IND,                   0),//4163(0x1043)
DECL_EVENT(NET_ACSM_NEW_ACU,                    0),//4164(0x1044)
DECL_EVENT(NET_ADSM_DATA_IND,                   0),//4165(0x1045)
DECL_EVENT(NET_ACSM_ACU_CLIENT_DISCONNECT_IND,  0),//4166(0x1046)
DECL_EVENT(NET_OAM_CRM_CLIENT_DISCONNECT_IND,   0),//4167(0x1047)
DECL_EVENT(NET_BMSM_NEW_DEVICE,                    0),
DECL_EVENT(NET_BMSM_DATA_IND,                   0),
DECL_EVENT(NET_BMSM_DEVICE_CLIENT_DISCONNECT_IND,  0),
DECL_EVENT(ADSM_RCII_ACU_DATA_REQ,          0),//4191(0x105F)//delete
DECL_EVENT(RCII_ADSM_ACU_DATA_RSP,          0),//4192(0x1060)//delete
DECL_EVENT(ACSM_ADSM_NEW_ACU_CFG_REQ,       0),//4193(0x1061)
DECL_EVENT(ADSM_ACSM_NEW_ACU_CFG_CFM,       0),//4194(0x1062)
DECL_EVENT(ACSM_ADSM_ACU_OFF_REQ,           0),//4195(0x1063)
DECL_EVENT(ADSM_ACSM_ACU_OFF_CFM,           0),//4196(0x1064)
DECL_EVENT(ADSM_ACSM_CHECK_ACU_ALIVE_REQ,   0),//4197(0x1065)
DECL_EVENT(ADSM_RCII_CHECKING_ACU_ALIVE_IND,0),//4198(0x1066)
DECL_EVENT(ACSM_ADSM_CHECK_ACU_ALIVE_RSP,   0),//4199(0x1067)
DECL_EVENT(ADSM_OAM_ACU_ROAD_INFO_IND,      0),//4200(0x1068)
DECL_EVENT(ADSM_OAM_ACU_COORDINATE_IND,     0),//4201(0x1069)
//DECL_EVENT(ACSM_OAM_BUS_INFO_RPT,           0),//4202(0x106A)
DECL_EVENT(ADSM_OAM_BUS_INFO_RPT,           0),//4202(0x106A)
DECL_EVENT(ACSM_OAM_ACU_BUS_CTRL_RPT,       0),//4203(0x106B)
DECL_EVENT(RCTP0_MC_INIT_IND, 0),//4223(0x108F)
DECL_EVENT(RCTP1_MC_INIT_IND, 0),//4224(0x1090)
DECL_EVENT(RCTP2_MC_INIT_IND, 0),//4225(0x1091)
DECL_EVENT(RCTP3_MC_INIT_IND, 0),//4226(0x1092)
DECL_EVENT(RCTP4_MC_INIT_IND, 0),//4227(0x1093)
DECL_EVENT(RCTP5_MC_INIT_IND, 0),//4228(0x1094)
DECL_EVENT(RCTP6_MC_INIT_IND, 0),//4229(0x1095)
DECL_EVENT(RCTP7_MC_INIT_IND, 0),//4230(0x1096)
DECL_EVENT(RCER_MC_INIT_IND, 0),//4231(0x1097)


DECL_EVENT(OAM_RCII_INIT_CONFIG_REQ, 0),//4232(0x1098)
DECL_EVENT(RCII_OAM_INIT_CONFIG_RSP, 0),//4233(0x1099)
DECL_EVENT(OAM_RCER_INIT_CONFIG_REQ, 0),//4234(0x109A)
DECL_EVENT(RCER_OAM_INIT_CONFIG_RSP, 0),//4235(0x109B)

DECL_EVENT(RCII_RCTP_DRSU_DATA_INFO_IND, 0),//4236(0x109C)
DECL_EVENT(RCII_RCTP_CLEAR_INVALID_DRSU_REQ, 0),//4237(0x109D)
DECL_EVENT(RCTP_RCII_CLEAR_INVALID_DRSU_RSP, 0),//4238(0x109E)
DECL_EVENT(ADSM_RCII_ACU_OBS_INF_REQ, 0),//4237(0x109D)
DECL_EVENT(RCTP_ADSM_ACU_OBS_INF_RSP, 0),//4238(0x109E)


DECL_EVENT(RCER_RCTP_EVENT_ANALYZE_REQ, 0),//4241(0x10A1)
DECL_EVENT(RCTP_RCER_EVENT_ANALYZE_RSP, 0),//4242(0x10A2)
DECL_EVENT(RCER_DCSM_TRAFFIC_WARNING_EVENT_START_IND, 0),//4243(0x10A3)
DECL_EVENT(RCER_DCSM_TRAFFIC_WARNING_EVENT_UPDATE_IND, 0),//4244(0x10A4)
DECL_EVENT(RCER_DCSM_TRAFFIC_WARNING_EVENT_END_IND, 0),//4245(0x10A5)
DECL_EVENT(RCER_OAM_SINGLE_VEHICLE_TRAFFIC_ACCIDENT_WARNING_IND, 0),//4246(0x10A6)
DECL_EVENT(RCER_OAM_TWO_VEHICLE_TRAFFIC_ACCIDENT_WARNING_IND, 0),//4247(0x10A7)
DECL_EVENT(RCER_OAM_MULTIPLE_VEHICLE_TRAFFIC_ACCIDENT_WARNING_IND, 0),//4248(0x10A8)
DECL_EVENT(RCER_OAM_SINGLE_VEHICLE_ABNORMAL_PARKING_WARNING_IND, 0),//4249(0x10A9)
DECL_EVENT(RCER_OAM_VEHICLE_CONVERSE_RUNNING_WARNING_IND, 0),//4250(0x10AA)
DECL_EVENT(RCER_OAM_LOW_SPEED_WARNING_IND, 0),//4251(0x10AB)
DECL_EVENT(RCER_OAM_ULTRA_LOW_SPEED_WARNING_IND, 0),//4252(0x10AC)
DECL_EVENT(RCER_OAM_TRAFFIC_JAM_WARNING_IND, 0),//4253(0x10AD)
DECL_EVENT(RCER_OAM_ROAD_CLOSE_WARNING_IND, 0),//4254(0x10AE)
DECL_EVENT(RCER_OAM_SPOILING_WARNING_IND, 0),//4255(0x10AF)
DECL_EVENT(RCER_OAM_ICING_WARNING_IND, 0),//4256(0x10B0)
DECL_EVENT(RCER_OAM_WET_SLIDING_WARNING_IND, 0),//4257(0x10B1)
DECL_EVENT(RCER_OAM_CLUSTER_FOG_WARNING_IND, 0),//4258(0x10B2)
DECL_EVENT(RCER_OAM_VIOLATION_PERSON_WARNING_IND, 0),//4259(0x10B3)
DECL_EVENT(RCER_OAM_ACCIDENT_RELIEVE_IND, 0),//4260(0x10B4)
DECL_EVENT(OAM_RCER_EVENT_RECOGNIZE_CONFIG_REQ, 0),//4261(0x10B5)
DECL_EVENT(RCER_OAM_EVENT_RECOGNIZE_CONFIG_RSP, 0),//4262(0x10B6)
DECL_EVENT(RCER_OAM_TWO_VEHICLE_ABNORMAL_PARKING_WARNING_IND, 0),//4263(0x10B7)

DECL_EVENT(OAM_DCSM_INIT_CFG_REQ, 0),//4264(0x10B8)
DECL_EVENT(DCSM_OAM_INIT_CFG_RSP, 0),//4265(0x10B9))
DECL_EVENT(OAM_RCTPX_INIT_CFG_REQ, 0),//4270(0x10BE)
DECL_EVENT(RCTPX_OAM_INIT_CFG_RSP, 0),//4271(0x10BF)
DECL_EVENT(OAM_ACSM_INIT_CFG_REQ, 0),//4272(0x10C0)
DECL_EVENT(ACSM_OAM_INIT_CFG_RSP, 0),//4273(0x10C1)
DECL_EVENT(OAM_ADSM_INIT_CFG_REQ, 0),//4274(0x10C2)
DECL_EVENT(ADSM_OAM_INIT_CFG_RSP, 0),//4275(0x10C3)
DECL_EVENT(OAM_BMSM_INIT_CFG_REQ, 0),
DECL_EVENT(OAM_BMSM_OAM_REGISTED_IND, 0),
DECL_EVENT(BMSM_OAM_INIT_CFG_RSP, 0),

DECL_EVENT(RCII_DCSM_NOT_RECEIVED_DATA_IND, 0),//4276(0x10C4)
DECL_EVENT(RCII_RCTP_ACU_OBS_INF_REQ, 0),//4277(0x10C5)


DECL_EVENT(RCER_OAM_EXCEED_SPEED_WARNING_IND, 0),//4282(0x10CA)
DECL_EVENT(OAM_RCER_CRM_OFF_LINE_IND, 0),//4283(0x10CB)
DECL_EVENT(OAM_RCER_CRM_ON_LINE_IND, 0),//4284(0x10CC)

DECL_EVENT(BMSM_OAM_NEW_BANMA_REQ, 0),
DECL_EVENT(OAM_BMSM_NEW_BANMA_RSP, 0),
DECL_EVENT(BMSM_OAM_BANMA_CONNECT_IND, 0),
DECL_EVENT(BMSM_OAM_BANMA_DISCONNECT_IND, 0),
DECL_EVENT(OAM_BMSM_BANMA_ONLINE_LIST_REQ, 0),
DECL_EVENT(BMSM_OAM_BANMA_ONLINE_LIST_RSP, 0),

DECL_EVENT(BMSM_RCTP_2D_DATA_REQ, 0),
DECL_EVENT(RCTP_BMSM_2D_DATA_RSP, 0),
DECL_EVENT(BMSM_MC_INIT_IND,0),
DECL_EVENT(RCII_RCTP_ALL_2D_DATA_INFO_REQ, 0),
DECL_EVENT(RCTP_OAM_ALL_2D_DATA_INFO_RSP, 0),

DECL_EVENT(RCER_OAM_ROAD_MAINTENANCE_WARNING_IND, 0),
DECL_EVENT(DCSM_RCER_IP_CAM_STATUS_IND, 0),
DECL_EVENT(RCER_OAM_OCCUPY_EMERGENCY_LANE_WARNING_IND, 0),

DECL_EVENT(OAM_RCTP_ALL_2D_DATA_INFO_CFM, 0),
DECL_EVENT(RCER_OAM_TRUCK_OCCUPY_THE_FAST_LANE_WARNING_IND, 0),
DECL_EVENT(ADSM_BMSM_ACU_STATE_IND,0),

DECL_EVENT(MQTT_MC_INIT_IND,0),
DECL_EVENT(OAM_MQTT_INIT_CFG_REQ,0),
DECL_EVENT(MQTT_OAM_INIT_CFG_RSP,0),
DECL_EVENT(TO_MQTT_DATA_IND,0),

DECL_EVENT(ADSM_BMSM_BRAKE_STATE_IND,0),
DECL_EVENT(OAM_ACSM_OAM_REGISTED_IND,0),

DECL_EVENT(MQTT_BMSM_DIS_IND,0),

DECL_EVENT(RCER_OAM_VEHICLE_TRAFFIC_ACCIDENT_WARNING_IND, 0),
DECL_EVENT(RCER_OAM_VEHICLE_ABNORMAL_PARKING_WARNING_IND, 0),
DECL_EVENT(BMSM_OAM_BANMA_CLIENT_INFO_IND, 0),//4320(0x10e0)


DECL_BEGIN(DRC_INTER_BEGIN_MSG_2, 0, (EVENT_SEG_LEN*17)),//4352(0x1100)
DECL_EVENT(CFGCMD_MC_INIT_IND, 0),
DECL_EVENT(OAM_CFGCMD_INIT_CFG_REQ, 0),
DECL_EVENT(CFGCMD_OAM_INIT_CFG_RSP, 0),
DECL_EVENT(OAM_CFGCMD_DRC_REGISTER_IND,0),
DECL_EVENT(CFG_ADSM_ACUSTATE_TO_VT_SWITCH_REQ, 0),
DECL_EVENT(ADSM_CFG_ACUSTATE_TO_VT_SWITCH_RSP,0),
DECL_EVENT(CFG_ADSM_ACUSTATE_TO_VT_SWITCH_QUERY_REQ, 0),
DECL_EVENT(ADSM_CFG_ACUSTATE_TO_VT_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_ADSM_ACUBRAKEINFO_TO_VT_SWITCH_REQ, 0),
DECL_EVENT(ADSM_CFG_ACUBRAKEINFO_TO_VT_SWITCH_RSP,0),
DECL_EVENT(CFG_ADSM_ACUBRAKEINFO_TO_VT_SWITCH_QUERY_REQ, 0),
DECL_EVENT(ADSM_CFG_ACUBRAKEINFO_TO_VT_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_RCER_EVENT_RECOGNIZE_SWITCH_REQ, 0),
DECL_EVENT(RCER_CFG_EVENT_RECOGNIZE_SWITCH_RSP,0),
DECL_EVENT(CFG_RCER_EVENT_RECOGNIZE_SWITCH_QUERY_REQ, 0),
DECL_EVENT(RCER_CFG_EVENT_RECOGNIZE_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_ACSM_ALLACU_VIDEO_SWITCH_QUERY_REQ, 0),
DECL_EVENT(ACSM_CFG_ALLACU_VIDEO_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_ACSM_ALLACU_OBSTACLE_SWITCH_QUERY_REQ, 0),
DECL_EVENT(ACSM_CFG_ALLACU_OBSTACLE_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_RCII_TWOD_ALLDRSU_SWITCH_REQ, 0),
DECL_EVENT(RCII_CFG_TWOD_ALLDRSU_SWITCH_RSP,0),
DECL_EVENT(CFG_RCII_TWOD_ALLDRSU_SWITCH_QUERY_REQ, 0),
DECL_EVENT(RCII_CFG_TWOD_ALLDRSU_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_RCII_THREED_ALLDRSU_SWITCH_REQ, 0),
DECL_EVENT(RCII_CFG_THREED_ALLDRSU_SWITCH_RSP,0),
DECL_EVENT(CFG_RCII_THREED_ALLDRSU_SWITCH_QUERY_REQ, 0),
DECL_EVENT(RCII_CFG_THREED_ALLDRSU_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_ADSM_REDIS_SWITCH_IND, 0),
DECL_EVENT(CFG_BMSM_REDIS_SWITCH_IND, 0),
DECL_EVENT(CFG_OAM_REDIS_SWITCH_IND, 0),
DECL_EVENT(CFG_RCTP_REDIS_SWITCH_IND, 0),
DECL_EVENT(CFG_ADSM_REDIS_SWITCH_QUERY_REQ, 0),
DECL_EVENT(ADSM_CFG_REDIS_SWITCH_QUERY_RSP,0),
DECL_EVENT(CFG_BMSM_TRAJECTORYMATCH_SWITCH_IND, 0),
DECL_EVENT(CFG_BMSM_TRAJECTORYMATCH_SWITCH_QUERY_REQ, 0),
DECL_EVENT(BMSM_CFG_TRAJECTORYMATCH_SWITCH_QUERY_RSP, 0),
DECL_EVENT(ACSM_OAM_ACU_VIDEO_DATA_RPT, 0),
DECL_EVENT(OAM_ACSM_ALLACU_VIDEO_SWITCH_CMD,0),
DECL_EVENT(RCER_OAM_OCCUPY_BUS_LANE_WARNING_IND, 0),
DECL_EVENT(BMSM_RCTP_TAJECTOR_MATCH_REQ, 0),
DECL_EVENT(RCTP_BMSM_TAJECTOR_MATCH_RSP,0),


DECL_EVENT(RCII_RCTP_DATA_INTIGRATION_IND, 0),
DECL_EVENT(RCTP0_OAM_INTIGRATION_DATA_IND, 0),

DECL_EVENT(VTSM_MC_INIT_IND,0),
DECL_EVENT(VTSM_REGC_MC_INIT_IND,0),
DECL_EVENT(VTSM_RECM_MC_INIT_IND,0),
DECL_EVENT(VTSM_MC_REGC_READY_IND,0),
DECL_EVENT(NET_VTSM_REGC_CLIENT_DISCONNECT_IND,0),
DECL_EVENT(VTSM_REGC_RECM_INIT_CFG_REQ,0),
DECL_EVENT(NET_VTSM_REGC_DATA_IND,0),
DECL_EVENT(VTSM_REGC_VTSM_CFG_IND,0),
DECL_EVENT(VTSM_REGC_VTSM_CFG_REQ,0),
DECL_EVENT(VTSM_VTSM_REGC_CFG_RSP,0),
DECL_EVENT(ACU_VTSM_ACU_STATE_IND,0),
DECL_EVENT(ADSM_VTSM_ACU_BRAKE_STATE_IND,0),
DECL_EVENT(VTSM_REGC_RECM_INIT_FINISH_IND,0),
DECL_EVENT(VTSM_REGC_VTSM_INIT_FINISH_IND,0),
DECL_EVENT(NET_VTSM_NEW_DEVICE,0),
DECL_EVENT(NET_VTSM_DATA_IND,0),
DECL_EVENT(NET_VTSM_DEVICE_CLIENT_DISCONNECT_IND,0),
DECL_EVENT(VTSM_VTSM_REGC_VT_POSITION_IND, 0),
DECL_EVENT(VTSM_REGC_START_CFG_IND,0),
DECL_EVENT(VTSM_RECM_REGC_CFG_RSP,0),
DECL_EVENT(VTSM_REGC_RECM_CFG_REQ,0),
DECL_EVENT(RECM_VTSM_VTSM_ACU_STATE_IND,0),

DECL_EVENT(RCTP_REGC_MC_INIT_IND,0),
DECL_EVENT(RCTP_RECM_MC_INIT_IND,0),
DECL_EVENT(RCTP_MC_REGC_READY_IND,0),


DECL_EVENT(NET_REGC_DATA_IND,0),
DECL_EVENT(RCTP_REGC_RCTPX_INIT_CFG_REQ,0),
DECL_EVENT(RCTP_REGC_RCTPX_INIT_CFG_RSP,0),
DECL_EVENT(RCTP_REGC_RECM_INIT_CFG_REQ,0),
DECL_EVENT(RCTP_RECM_REGC_INIT_CFG_RSP,0),
DECL_EVENT(RCTP_REGC_RECM_WORK_IND,0),
DECL_EVENT(RCTP_RECM_RCTP_DRSU_IND,0),
DECL_EVENT(RCTP_RCTP_REGC_ALL_2D_DATA_INFO_REQ,0),

DECL_EVENT(RCTP_REGC_RCTP_ALL_2D_DATA_INFO_CFM,0),
DECL_EVENT(RCTP_REGC_RECR_WAKE_UP_IND,0),
DECL_EVENT(RCTP_REGC_RCTP_EVENT_ANALYZE_REQ,0),
DECL_EVENT(RCTP_REGC_RCTP_ALL_2D_DATA_INFO_REQ, 0),
DECL_EVENT(RCTP_REGC_RCTP_DRSU_DATA_INFO_IND, 0),
DECL_EVENT(RCTP_REGC_REGC_TCI_TIMER_IND, 0),
DECL_EVENT(RCTP_REGC_RCTP_TCI_REQ_IND, 0),
DECL_EVENT(RCTP_RCTP_REGC_TCI_RSP_IND, 0),