/*
 * decl_event_drc_banma.h
 *
 *  Created on: Jul 20, 2020
 *      Author: wenhan
 */

/*----------DRC和Banma设备交互消息定义---------*/

DECL_BEGIN(DRC_BANMA_BEGIN_MSG,       0, (EVENT_SEG_LEN*250)),//64000
DECL_EVENT(BANMA_MSG_TYPE_CONNECT_REQ,       0),	
DECL_EVENT(BANMA_MSG_TYPE_CONNECT_RSP,       0),	
DECL_EVENT(BANMA_MSG_TYPE_POSITION_REQ,       0),	
DECL_EVENT(BANMA_MSG_TYPE_POSITION_RSP,       0),	
DECL_EVENT(BANMA_MSG_TYPE_DISCONNECT_REQ,       0),	
DECL_EVENT(BANMA_MSG_TYPE_DISCONNECT_COMMAND,       0),
DECL_EVENT(BANMA_MSG_TYPE_DISCONNECT_COMPLETE,       0),
DECL_EVENT(BANMA_MSG_TYPE_ACU_STATE_IND,       0),
DECL_EVENT(BANMA_MSG_TYPE_EMERGENC_YBRAKE_WARNING,       0),
DECL_EVENT(BANMA_MSG_TYPE_QUIT_EMERGENCY_LANEIND,       0),


