

////////////////////////MODULE NAME FOR LOG PRINT ONLY/////////////////////
DECL_LOGMODULE(MODULE_COMM),

DECL_LOGMODULE(PLATFORM_INTER_MSG),
DECL_LOGMODULE(PLATFORM_MBOX),
DECL_LOGMODULE(PLATFORM_EX),
DECL_LOGMODULE(PLATFORM_ROOT),
DECL_LOGMODULE(PLATFORM_LOG),
DECL_LOGMODULE(MODULE_DRC_COMMON),
DECL_LOGMODULE(LOG_MODULE_MAX)


