/*******************************************************************************
  Copyright (C), 2012, Innofidei Inc
  File name:    pf_timer.h

  Author:       Version:        Date: 
  Lou Junqing   1.0             2012-11-15
  
  Description:  This file declares timer common structure and types.

  Function List:

  History:
  <Author>      <Date>      <Version>   <description>           
  Lou Junqing   2012-11-15  1.0         First implementation of timer service

*******************************************************************************/
#ifndef _PF_TIMER_H
#define _PF_TIMER_H

#include <pl_type.h>
#include <event.h>
#include <vector>

#define PF_INVALID_TIMER_ID     0xFFFFFFFF
//#define PF_FRAME_PERIOD_SIZE    4096

/* 1ms timer service parameters */
#define DRC_MAX_TIMER_NUM_1MS      10000    /* must <= 16383, check PF_TIMER_ARRAY_MAX_SIZE */
#define DRSU_MAX_TIMER_NUM_1MS     1000     /* must <= 16383, check PF_TIMER_ARRAY_MAX_SIZE */

//进程Timer总数配置文件路径
#define MAX_TIMER_NUMBER_FILE      "/config/bootup/max_timer_number"



typedef enum {
    PF_TIMER_SUCCESS = 0,       // 0: success
    PF_TIMER_FAIL,              // 1: fail
    PF_TIMER_PARAM_ERROR,       // 2: parameter error
    PF_TIMER_NOT_EXIST,         // 3: not exist
    PF_TIMER_NOT_PERMIT,        // 4: not permitted
    PF_TIMER_NO_RESOURCE,       // 5: no resource
    PF_TIMER_OUT_OF_SERVICE,    // 6: no resource
} PF_TIMER_RETURN_VALUE_E;
    
typedef struct
{
    U32 ulTimerId;
    U32 ulTypeId;
    U64 ullPara; 
} TIMER_EXPIRE_MSG_S;  

typedef struct 
{
    U32 ulFrameTimer;
    U32 ulSubFrameTimer; 
} FRAME_REPORT_IND_S; //platform to MODULE_DRC_RCII

typedef enum {
    PF_TIMER_TICK_INTERVAL_1MS = 1,
    PF_TIMER_TICK_INTERVAL_10MS = 10,    
} PF_TIMER_TICK_INTERVAL_VALUE_E;


/*******************************************************************************
*  Function:    pf_timer_start
*
*  Description: Setup a one-shot timer to timer manager. Return error code.
*
*  Input:       usSrcModuleId   application module ID. used as timer expire message receiver. 
*                               the caller shall make sure it is a valid value.
*               ulDuration      timer duration in millisec.
*               ulTypeId        application timer type ID. not used by timer manager.
*               ullParam        application timer parameter. not used by timer manager.
*
*  Output:      pulTimerId      generated timer ID, used for index a timer.
*
*  Return:      PF_TIMER_SUCCESS        timer setup succeeded.
*               PF_TIMER_NO_RESOURCE    no free timer resource. timer setup failed.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*               PF_TIMER_PARAM_ERROR    input parameter error.
*
*******************************************************************************/
U32 pf_timer_start(U32 ulSrcModuleId, U32 ulDuration, U32 ulTypeId, U64 ullParam, U32* pulTimerId);

/*******************************************************************************
*  Function:    pf_timer_cycle_start
*
*  Description: Setup a cycle timer to timer manager. Return error code.
*
*  Input:       usSrcModuleId   application module ID. used as timer expire message receiver. 
*                               the caller shall make sure it is a valid value.
*               ulDuration      timer duration in millisec.
*               ulTypeId        application timer type ID. not used by timer manager.
*               ullParam        application timer parameter. not used by timer manager.
*
*  Output:      pulTimerId      generated timer ID, used for index a timer.
*
*  Return:      PF_TIMER_SUCCESS        timer setup succeeded.
*               PF_TIMER_NO_RESOURCE    no free timer resource. timer setup failed.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*               PF_TIMER_PARAM_ERROR    input parameter error.
*
*******************************************************************************/
U32 pf_timer_cycle_start(U32 ulSrcModuleId, U32 ulDuration, U32 ulTypeId, U64 ullParam, U32* pulTimerId);

/*******************************************************************************
*  Function:    pf_timer_stop
*
*  Description: kill a timer from timer manager. Return error code.
*
*  Input:       ulTimerId       timer ID. it must be the same one generated by 
*                               pf_timer_start or pf_timer_cycle_start.
*               usSrcModuleId   application module ID. it must be the same one 
*                               when setup this timer.
*
*  Output:      
*
*  Return:      PF_TIMER_SUCCESS        timer delete succeeded.
*               PF_TIMER_PARAM_ERROR    timer ID is invalid. probably random value.
*               PF_TIMER_NOT_PERMIT     timer ID is valid, but module ID is wrong.
*               PF_TIMER_NOT_EXIST      timer ID may be valid, but it is not running.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*
*******************************************************************************/
U32 pf_timer_stop(U32 ulTimerId, U32 ulSrcModuleId);

/*******************************************************************************
*  Function:    pf_is_set_timer_internal
*
*  Description: query a timer from 10ms timer manager. Return error code.
*               this function is only for debug and MT.
*
*  Input:       u32TimerId      timer ID. it must be the same one generated by tm_set_timer.
*               u16ModuleId     application module ID. it must be the same one 
*                               when setup this timer.
*
*  Output:      
*
*  Return:      PF_TIMER_SUCCESS        timer query succeeded. the timer is running.
*               PF_TIMER_PARAM_ERROR    timer ID is invalid. probably random value.
*               PF_TIMER_NOT_PERMIT     timer ID is valid, but module ID is wrong.
*               PF_TIMER_NOT_EXIST      timer ID may be valid, but it is not running.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*
*******************************************************************************/
U32 pf_is_set_timer_internal(U32 u32TimerId, U32 u32ModuleId);

/*******************************************************************************
*  Function:    pf_timer_restart
*
*  Description:Used to restart the specified timer
*
*  Input:       ulTimerId       timer ID. it must be the same one generated by 
*                               pf_timer_start or pf_timer_cycle_start.
*               ulSrcModuleId   application module ID. it must be the same one 
*                               when setup this timer.
*
*  Output:      
*
*  Return:      PF_TIMER_SUCCESS        timer restart succeeded.
*               PF_TIMER_PARAM_ERROR    timer ID is invalid. probably random value.
*               PF_TIMER_NOT_PERMIT     timer ID is valid, but module ID is wrong.
*               PF_TIMER_NOT_EXIST      timer ID may be valid, but it is not running.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*
*******************************************************************************/
U32 pf_timer_restart(U32 ulTimerId, U32 ulSrcModuleId);

/*******************************************************************************
*  Function:    pf_timer_frame_data_start
*
*  Description: query a timer which output the frame number to the modules every 100ms 
*
*  Input:       aulDstModuleId  the vector of module index.
*
*  Output:      
*
*  Return:      PF_TIMER_SUCCESS        timer query succeeded. the timer is running.
*               PF_TIMER_PARAM_ERROR    timer ID is invalid. probably random value.
*               PF_TIMER_OUT_OF_SERVICE timer service is not available.
*
*******************************************************************************/
U32 pf_timer_frame_data_start(std::vector<U32> aulDstModuleId);


#endif /* end of #ifndef _PF_TIMER_H */

