/************************************************************
  Copyright (C), BroadXT Inc  2019
  FileName: pl_counts.h
  Author: josephzhou    Version :  1.0   Date: 20190606
  Description:     Platform Counter slInterface Header File
  Function List:    
    1. -------
  History:          
  <author>      <time>          <version >   <desc>
  josephzhou    2019/06/06         0.1        initial
***********************************************************/
#ifndef _PL_COUNTS_H
#define _PL_COUNTS_H

/*Counter index, each module defines itself according to its own needs£¬range 0~CI_MAX*/

#define CI_MAX 256


/*module number£¬range: 0 ~ CM_MAX*/
typedef enum
{
    CM_TMP  = 0,                            /*using for locate problem*/
    CM_COM  = 1,                            /*common statistics*/
    CM_FMSG = 2,                            /*msgQueue send failed message statistics*/
    CM_SMSG = 3,                            /*msgQueue send message statistics*/
    CM_RMSG = 4,                            /*msgQueue received message statistics*/
    CM_LCOM = 5,                            /*last cycle common statistics*/
    CM_LFMSG = 6,                           /*last cycle msgQueue send failed message statistics*/
    CM_LSMSG = 7,                           /*last cycle msgQueue send message statistics*/
    CM_LRMSG = 8,                           /*last cycle msgQueue received message statistics*/
    CM_PES  = 9,                            /*platform error statistics*/
    CM_NES  = 10,                           /*network error statistics*/
    CM_PFPS = 11,                           /*platform function performance statistics*/
    CM_PTI  = 12,                           /*platform trace information*/
    CM_PRA  = 13,                           /*platform reserve area*/
    CM_MTT  = 14,                           /*platform msg entry total time*/
    CM_MMAX = 15,                           /*platform msg entry maximum timer interval*/
    CM_MMID = 16,                           /*platform msg entry msgId of the maximum interval*/
    CM_MAX  = 32
}COUNT_MODULE_TYPE;

extern U64 g_ulPSCnts[CM_MAX][CI_MAX];      /*counter*/


/*Counter operation macro encapsulation, please use macro-to-counter operation to facilitate future expansion*/

#ifdef MEMORY_STATICS 
/*Initialize counters for all modules*/
#define PS_CInit                            pf_memset((void *)g_ulPSCnts, 0, sizeof(g_ulPSCnts))

/*The value of index of module mid is added by 1*/
#define PS_CPlus(mid, index)                {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index]++;}

/*The value of index of module mid is added by Value*/
#define PS_CPlusV(mid, index, value)        {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index] += value;}

/*The value of index of module mid decreases by 1*/
#define PS_CMinus(mid, index)               {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index]--;}

/*The value of index of module mid decreases by value*/
#define PS_CMinusV(mid, index, value)       {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index] -= value;}

/*The value of index of module mid is set to 0*/
#define PS_CReset(mid, index)               {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index] = 0;}

/*The value of index of module mid is set to value*/
#define PS_CSet(mid, index, value)          {if((mid < CM_MAX) && (index < CI_MAX))g_ulPSCnts[mid][index] = value;}

/*Get the count value of index of module mid*/
#define PS_CGet(mid, index)                 g_ulPSCnts[mid][index]

/*The count value of index value of module mid is the maximum value of max*/
#define PS_CMax(mid, index, max)            {if((mid < CM_MAX) && (index < CI_MAX)){                    \
                                                if(g_ulPSCnts[mid][index] < max)                        \
                                                    g_ulPSCnts[mid][index] = max;}}

/*The count value of index value of module mid is the minimum value of min*/
#define PS_CMin(mid, index, min)            {if((mid < CM_MAX) && (index < CI_MAX)){                    \
                                                if(g_ulPSCnts[mid][index] > min)                        \
                                                    g_ulPSCnts[mid][index] = min;}}

//#define CMPFPS_PS_CPlus(index)              {if(index < CI_MAX)g_ulPSCnts[CM_PFPS][index]++;}
//#define CMPFPS_PS_CPlusV(index, value)      {if(index < CI_MAX)g_ulPSCnts[CM_PFPS][index] += value;}

#define CMPFPS_PS_CPlus(index)              {if(index < CI_MAX)g_ulPSCnts[CM_PFPS][index]++;}
#define CMPFPS_PS_CPlusV(index, value)      {if(index < CI_MAX)g_ulPSCnts[CM_PFPS][index] += value;}


#else
/*Initialize counters for all modules*/
#define PS_CInit

/*The value of index of module mid is added by 1*/
#define PS_CPlus(mid, index)

/*The value of index of module mid is added by Value*/
#define PS_CPlusV(mid, index, value)

/*The value of index of module mid decreases by 1*/
#define PS_CMinus(mid, index)

/*The value of index of module mid decreases by value*/
#define PS_CMinusV(mid, index, value)

/*The value of index of module mid is set to 0*/
#define PS_CReset(mid, index)

/*The value of index of module mid is set to value*/
#define PS_CSet(mid, index, value)

/*Get the count value of index of module mid*/
#define PS_CGet(mid, index)                 g_ulPSCnts[mid][index]

/*The count value of index value of module mid is the maximum value of max*/
#define PS_CMax(mid, index, max)

/*The count value of index value of module mid is the minimum value of min*/
#define PS_CMin(mid, index, min)

#define CMPFPS_PS_CPlus(index)               

#define CMPFPS_PS_CPlusV(index, value)       
#endif

/***********Index partition of common statistic counter***********/
typedef enum
{
    CMCOM_ID_MALLOC_CNT,
    CMCOM_ID_MALLOC_SIZE, 
    CMCOM_ID_COMMBUF_MALLOC_CNT,
    CMCOM_ID_COMMBUF_FREE_CNT,
    CMCOM_ID_FREE_CNT,
    CMCOM_ID_MEMCPY_CNT,
    CMCOM_ID_MEMCPY_SIZE, 
    CMCOM_ID_MEMSET_CNT,
    CMCOM_ID_MEMSET_SIZE, 
    CMCOM_ID_REALLOC_CNT,
    CMCOM_ID_REALLOC_SIZE, 
    CMCOM_ID_GET_TICKS_MS_CNT,
    CMCOM_ID_GET_TICKS_US_CNT,
    CMCOM_ID_GET_TICKS_NS_CNT,
    CMCOM_ID_USLEEP_TOTAL_CNT,
    CMCOM_ID_THREAD_CREATE_TOTAL_CNT,
    CMCOM_ID_THREAD_CREATE_MID_TOTAL_CNT,
    CMCOM_ID_WRITE_FLUSH_TOTAL_CNT,
    CMCOM_ID_WRITE_FLUSH_CNT,
    CMCOM_ID_WRITE_FLUSH_SIZE, 
    CMCOM_ID_WRITE_ENDOF_TOTAL_CNT,
    CMCOM_ID_WRITE_ENDOF_CNT,
    CMCOM_ID_WRITE_ENDOF_SIZE, 
    CMCOM_ID_COPYMSG_ENDOF_TOTAL_CNT,
    CMCOM_ID_COPYMSG_ENDOF_CNT,
    CMCOM_ID_COPYMSG_ENDOF_SIZE, 
    CMCOM_ID_READ_FLUSH_TOTAL_CNT,
    CMCOM_ID_READ_FLUSH_CNT,
    CMCOM_ID_READ_FLUSH_SIZE, 
    CMCOM_ID_GET_FILE_TOTAL_CNT,
    CMCOM_ID_GET_FILE_CNT,
    CMCOM_ID_LOG_TOTAL_CNT,
    CMCOM_ID_LOG_CNT,
    CMCOM_ID_LOG_SEND_CNT,
    CMCOM_ID_LOG_RETURN_CNT,
    CMCOM_ID_LOG_NULL_CNT,
    CMCOM_ID_DUMP_TOTAL_CNT,
    CMCOM_ID_DUMP_RET_CNT,
    CMCOM_ID_DUMP_NULL_CNT,
    CMCOM_ID_DUMP_CNT,
    CMCOM_ID_COPY_MSG_IN_CNT,
    CMCOM_ID_COPY_MSG_CNT,
    CMCOM_ID_COPY_MSG_MALLOC_CNT,
    CMCOM_ID_COPY_MSG_FREE_CNT,
    CMCOM_ID_COPY_MSG_SIZE_L,
    CMCOM_ID_COPY_TRY_MSG_IN_CNT,
    CMCOM_ID_COPY_TRY_MSG_CNT,
    CMCOM_ID_COPY_TRY_MSG_SIZE_L, 
    CMCOM_ID_GET_MSG_CNT,
    CMCOM_ID_TIMER_START_CNT,
    CMCOM_ID_TIMER_CYCLE_START_CNT,
    CMCOM_ID_TIMER_STOP_CNT,
    CMCOM_ID_TIMER_RESTART_CNT,
    CMCOM_ID_SEND_UDP_CNT,
    CMCOM_ID_SEND_UDP_SIZES_L,
    CMCOM_ID_SEND_UDP_SIZES_H,
    CMCOM_ID_SEND_SCTP_CNT,
    CMCOM_ID_SEND_SCTP_SIZES_L,
    CMCOM_ID_SEND_SCTP_SIZES_H,
    CMCOM_ID_SEND_TCP_CNT,
    CMCOM_ID_SEND_TCP_SIZES_L,
    CMCOM_ID_SEND_TCP_SIZES_H,
    CMCOM_ID_SEND_RAW_CNT,
    CMCOM_ID_SEND_RAW_SIZES_L,
    CMCOM_ID_SEND_RAW_SIZES_H,
    CMCOM_ID_RECV_UDP_CNT,
    CMCOM_ID_RECV_UDP_SIZES_L,
    CMCOM_ID_RECV_UDP_SIZES_H,
    CMCOM_ID_RECV_SCTP_CNT,
    CMCOM_ID_RECV_SCTP_SIZES_L,
    CMCOM_ID_RECV_SCTP_SIZES_H,
    CMCOM_ID_RECV_TCP_CNT,
    CMCOM_ID_RECV_TCP_SIZES_L,
    CMCOM_ID_RECV_TCP_SIZES_H,
    CMCOM_ID_RECV_RAW_CNT,
    CMCOM_ID_RECV_RAW_SIZES_L,
    CMCOM_ID_RECV_RAW_SIZES_H,
    CMCOM_ID_ADD_BUFFER_SIZE,
    CMCOM_ID_MOVE_BUFFER_SIZE,
    CMCOM_ID_RDKAFKA_PRODUCER_SEND_CNT,
    CMCOM_ID_RDKAFKA_PRODUCER_SEND_TOTAL_SIZE,
    CMCOM_ID_RDKAFKA_PRODUCER_DR_CB_CNT,
    CMCOM_ID_RDKAFKA_PRODUCER_EVENT_CB_CNT,
    CMCOM_ID_RDKAFKA_CONSUMER_EVENT_CB_CNT,
    CMCOM_ID_RDKAFKA_CONSUMER_CONFIGURE_EVENT_CB_CNT,
    CMCOM_ID_RDKAFKA_CONSUMER_CONFIGURE_FULL_EVENT_CB_CNT,
    CMCOM_ID_RDKAFKA_CONSUMER_REBALANCE_CB_CNT,
    CMCOM_ID_RDKAFKA_CONSUMER_CB_CNT,
    CMCOM_ID_LOG_MALLOC_CNT,
    CMCOM_ID_LOG_FREE_CNT,
    CMCOM_ID_THREAD_MID_UNMATCH_CNT,
    CMCOM_ID_THREAD_MID_OVERLAP_CNT,
#if 0
    /*delete for MR1421*/
    /*thread module offset of failed message queue*/
    CMCOM_ID_SEND_FAILED_MSGQ_MID_OFFSET = 0xA0,

    /*thread module offset of sender message queue*/
    CMCOM_ID_SEND_MSGQ_MID_OFFSET = 0xC0,
    
    /*thread module offset of receive message queue*/
    CMCOM_ID_RCVD_MSGQ_MID_OFFSET = 0xE0,
#endif
    CMCOM_ID_MAX,
}CM_COM_Index_Type;

/***********Index partition of thread module failed message queue statistic counter***********/
typedef enum
{
   /*thread module failed message queue*/
    CMFMSG_ID_SEND_FAILED_MSGQ_MID_OFFSET = 0x0,

}CM_FMSG_Index_Type;

/***********Index partition of thread module sending message queue statistic counter***********/
typedef enum
{
    /*thread module offset of sender message queue*/
    CMSMSG_ID_SEND_MSGQ_MID_OFFSET = 0x0,

}CM_SMSG_Index_Type;

/***********Index partition of thread module receive message queue statistic counter***********/
typedef enum
{
    /*thread module offset of receive message queue*/
    CMRMSG_ID_RCVD_MSGQ_MID_OFFSET = 0x0,

}CM_RMSG_Index_Type;



/***********Index partition of platform error statistic counter***********/
typedef enum
{
    CMPES_ID_COMMBUF_MALLOC_NULL = 0,
    CMPES_ID_COMMBUF_MALLOC_NULL_SIZE,
    CMPES_ID_COMMBUF_MALLOC_IN_NULL,
    CMPES_ID_COMMBUF_FREE_NULL,
    CMPES_ID_COMMBUF_CREATE_NULL,
    CMPES_ID_COMMBUF_CREATE_MAX_NUM,
    CMPES_ID_COMMBUF_CREATE_MALLOC_NULL,
    CMPES_ID_COMMBUF_CREATE_BUFSTART_NULL,
    CMPES_ID_COMMBUF_QUECTRL_NULL,
    CMPES_ID_COMMBUF_DESTROY_NULL,
    CMPES_ID_COMMBUF_DESTROY_BUF_NOT_EMPTY,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_MAX,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_NULL,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_NOT_MULTI,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_MALLOC_NULL,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_BUFEND_FAIL,
    CMPES_ID_COMMBUF_CREATE_ADDRESS_QUECTRL_NULL,
    CMPES_ID_COMMBUF_MUTEX_INIT_NULL,
    CMPES_ID_COMMBUF_GET_NULL,
    CMPES_ID_COMMBUF_GET_THREAD_FAIL,
    CMPES_ID_COMMBUF_GET_ADDRESS_FAIL,
    CMPES_ID_COMMBUF_GET_MALLOC_FAIL,
    CMPES_ID_COMMBUF_GET_FAIL,
    CMPES_ID_COMMBUF_RET_NULL,
    CMPES_ID_COMMBUF_RET_THREAD_FAIL,
    CMPES_ID_COMMBUF_RET_ADDRESS_FAIL,
    CMPES_ID_COMMBUF_RET_FAIL,
    CMPES_ID_COMMBUF_RET_PUT_FAIL,
    CMPES_ID_COMMBUF_AVAIL_NULL,
    CMPES_ID_COMMBUF_LOG_NULL,
    CMPES_ID_COMMBUF_QUE_CREATE_NUM_ERROR,
    CMPES_ID_COMMBUF_QUE_CREATE_MALLOC_CTRL_NULL,
    CMPES_ID_COMMBUF_QUE_CREATE_MALLOC_ELEM_NULL,
    CMPES_ID_COMMBUF_QUE_DESTROY_NULL,
    CMPES_ID_COMMBUF_QUE_DESTROY_NOT_FOUND,
    CMPES_ID_COMMBUF_QUE_GET_NULL,
    CMPES_ID_COMMBUF_QUE_GET_EMPTY,
    CMPES_ID_COMMBUF_QUE_PET_NULL,
    CMPES_ID_COMMBUF_QUE_PET_FULL,
    CMPES_ID_COMMBUF_QUE_AVAIL_NULL,
    CMPES_ID_MEMCPY_SRC_NULL,
    CMPES_ID_MEMCPY_DST_NULL,
    CMPES_ID_MEMCPY_SIZE_NULL,
    CMPES_ID_MEMSET_ADDRESS_NULL,
    CMPES_ID_MEMSET_SIZE_NULL,
    CMPES_ID_POOL_INIT_MALLOC_NULL,
    CMPES_ID_POOL_INIT_CREATE_NULL,
    CMPES_ID_MALLOC_ADDRESS_NULL,
    CMPES_ID_MALLOC_IN_NULL,
    CMPES_ID_REALLOC_IN_NULL,
    CMPES_ID_REALLOC_MALLOC_NULL,
    CMPES_ID_REALLOC_ADDRESS_NULL,
    CMPES_ID_FREE_IN_NULL,
    CMPES_ID_TICKS_MS_FAIL,
    CMPES_ID_TICKS_US_FAIL,
    CMPES_ID_TICKS_NS_FAIL,
    CMPES_ID_GET_TIMEOFDAY_FAIL,
    CMPES_ID_GET_FRAME_TIME_FAIL,
    CMPES_ID_USLEEP_GET_FAIL,
    CMPES_ID_USLEEP_NANO_FAIL,
    CMPES_ID_PTHREAD_ATTR_FAIL,
    CMPES_ID_PTHREAD_CREATE_FAIL,
    CMPES_ID_KERNEL_VERSION_FAIL,
    CMPES_ID_INET_ATON_FUNC_FAIL,
    CMPES_ID_INET_ATON_STR_FAIL,
    CMPES_ID_IFCONFIG_IN_NULL,
    CMPES_ID_IFCONFIG_SOCKET_FAIL,
    CMPES_ID_IFCONFIG_IOCTL_FAIL,
    CMPES_ID_IFCONFIG_MAC_IN_NULL,
    CMPES_ID_IPADDR_SET_FAIL,
    CMPES_ID_IPADDR_IFNAMSIZ_FAIL,
    CMPES_ID_IPADDR_SIOCGIFADDR1_FAIL,
    CMPES_ID_IPADDR_SIOCGIFADDR2_FAIL,
    CMPES_ID_GW_SET_FAIL,
    CMPES_ID_GW_SET_SOCKET_FAIL,
    CMPES_ID_GW_SET_SIOCDELRT_FAIL,
    CMPES_ID_NETMASK_SET_FAIL,
    CMPES_ID_NETMASK_SET_DEV_FAIL,
    CMPES_ID_NETMASK_SET_SOCKET_FAIL,
    CMPES_ID_NETMASK_SET_SIOCSIFNETMASK_FAIL,
    CMPES_ID_NETMASK_SET_SIOCSIFFLAGS_FAIL,
    CMPES_ID_SYSTEM_CALL_IN_NULL,
    CMPES_ID_SYSTEM_CALL_SAVE_FAIL,
    CMPES_ID_SYSTEM_CALL_FUNC_FAIL,
    CMPES_ID_SYSTEM_CALL_EXIT_CODE_FAIL,
    CMPES_ID_SYSTEM_CALL_EXIT_STATUS_FAIL,
    CMPES_ID_WRITE_FILE_IN_NULL,
    CMPES_ID_WRITE_FILE_OPEN_FAIL,
    CMPES_ID_WRITE_ENDOF_IN_NULL,
    CMPES_ID_WRITE_ENDOF_OPEN_FAIL,
    CMPES_ID_WRITE_ENDOF_ERASE_FAIL,
    CMPES_ID_READ_FILE_IN_NULL,
    CMPES_ID_READ_FILE_OPEN_FAIL,
    CMPES_ID_GET_FILE_LENGTH_IN_NULL,
    CMPES_ID_READ_FILE_INLINE_IN_NULL,
    CMPES_ID_GET_SYSINFO_IN_NULL,
    CMPES_ID_GET_SYSINFO_READ_MEMINFO_FAIL,
    CMPES_ID_GET_SYSINFO_READ_STATUS_FAIL,
    CMPES_ID_FTP_CMD_OPEN_NULL,
    CMPES_ID_FTP_CMD_FGETS_NULL,
    CMPES_ID_FTP_GET_PORT_INET_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_SOCKET_FAIL,
    CMPES_ID_FTP_GET_PORT_CONNECT_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_NULL,
    CMPES_ID_FTP_GET_PORT_CMD_USER_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_PASS_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_TYPEI_FAIL,
    CMPES_ID_FTP_GET_PORT_DATA_SOCKET_FAIL,
    CMPES_ID_FTP_GET_PORT_BIND_FAIL,
    CMPES_ID_FTP_GET_PORT_LISTEN_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_PORT_FAIL,
    CMPES_ID_FTP_GET_PORT_CMD_RETR_FAIL,
    CMPES_ID_FTP_GET_PORT_ACCEPT_FAIL,
    CMPES_ID_FTP_GET_PORT_OPEN_FAIL,
    CMPES_ID_FTP_GET_PORT_RETURN_FAIL,
    CMPES_ID_FTP_PUT_PORT_INET_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_SOCKET_FAIL,
    CMPES_ID_FTP_PUT_PORT_CONNECT_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_NULL,
    CMPES_ID_FTP_PUT_PORT_CMD_USER_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_PASS_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_TYPEI_FAIL,
    CMPES_ID_FTP_PUT_PORT_DATA_SOCKET_FAIL,
    CMPES_ID_FTP_PUT_PORT_BIND_FAIL,
    CMPES_ID_FTP_PUT_PORT_LISTEN_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_PORT_FAIL,
    CMPES_ID_FTP_PUT_PORT_CMD_STOR_FAIL,
    CMPES_ID_FTP_PUT_PORT_ACCEPT_FAIL,
    CMPES_ID_FTP_PUT_PORT_OPEN_FAIL,
    CMPES_ID_FTP_PUT_PORT_RETURN_FAIL,
    CMPES_ID_FTP_XATOU_FAIL,
    CMPES_ID_FTP_XATOU2SOCK_FAIL,
    CMPES_ID_FTP_XATOU2SOCK_MALLOC_FAIL,
    CMPES_ID_FTP_SOCKADDR2STR_GETNAME_FAIL,
    CMPES_ID_FTP_SOCKADDR2STR_FLAGS_FAIL,
    CMPES_ID_FTP_XOPEN3_FAIL,
    CMPES_ID_FTP_FULL_WRITE_FAIL,
    CMPES_ID_FTP_FULL_ACTION_FD_FAIL,
    CMPES_ID_FTP_FULL_ACTION_SIZE_FAIL,
    CMPES_ID_FTP_FULL_ACTION_RD_FAIL,
    CMPES_ID_FTP_FULL_ACTION_WRITE_FAIL,
    CMPES_ID_FTP_CMD_FGETS_FAIL,
    CMPES_ID_FTP_LOGIN_CONNECT_FAIL,
    CMPES_ID_FTP_LOGIN_FDOPEN_FAIL,
    CMPES_ID_FTP_LOGIN_FTPCMD_FAIL,
    CMPES_ID_FTP_LOGIN_PASS_FAIL,
    CMPES_ID_FTP_LOGIN_USER_FAIL,
    CMPES_ID_FTP_LOGIN_TYPEI_FAIL,
    CMPES_ID_FTP_SEND_PASV_FAIL,
    CMPES_ID_FTP_SEND_FTPDATA_FAIL,
    CMPES_ID_FTP_SEND_XOPEN_FAIL,
    CMPES_ID_FTP_SEND_ALLO_FAIL,
    CMPES_ID_FTP_SEND_STOR_FAIL,
    CMPES_ID_FTP_SEND_BBEOF_FAIL,
    CMPES_ID_FTP_SEND_CLOSE_FAIL,
    CMPES_ID_FTP_RECIEVE_PASV_FAIL,
    CMPES_ID_FTP_RECIEVE_RETR_FAIL,
    CMPES_ID_FTP_RECIEVE_XOPEN_FAIL,
    CMPES_ID_FTP_RECIEVE_COPYFD_FAIL,
    CMPES_ID_FTP_RECIEVE_CLOSE_FAIL,
    CMPES_ID_FTP_GET_PASV_RECIEVE_FAIL,
    CMPES_ID_FTP_GET_PASV_INFO_RECIEVE_FAIL,
    CMPES_ID_FTP_GET_PASV_ENCINFO_RECIEVE_FAIL,
    CMPES_ID_FTP_PUT_PASV_SEND_FAIL,
    CMPES_ID_FTP_PUT_PASV_INFO_SEND_FAIL,
    CMPES_ID_LOG_MUTEXATTR_INIT_FAIL,
    CMPES_ID_LOG_MUTEXATTR_SET_FAIL,
    CMPES_ID_LOG_MUTEX_INIT_FAIL,
    CMPES_ID_PF_LOG_CTRL_FULL_FAIL,
    CMPES_ID_PF_LOG_DATA_FULL_FAIL,
    CMPES_ID_PF_DUMP_CTRL_FULL_FAIL,
    CMPES_ID_PF_DUMP_DATA_FULL_FAIL,
    CMPES_ID_LOG_INIT_FOPEN_FAIL,
    CMPES_ID_COPY_MSG_IN_FAIL,
    CMPES_ID_COPY_MSGQ_NULL,
    CMPES_ID_COPY_MSG_MALLOC_NULL,
    CMPES_ID_COPY_TRY_MSG_IN_FAIL,
    CMPES_ID_COPY_TRY_MSGQ_NULL,
    CMPES_ID_COPY_TRY_MSG_MALLOC_NULL,
    CMPES_ID_MBOX_TRY_GET_NULL,
    CMPES_ID_MBOX_TRY_PUT_FULL,
    CMPES_ID_MBOX_TRY_PUT_COPY_FULL,
    CMPES_ID_MBOX_TRY_LOCK_PUT_FAIL,
    CMPES_ID_MBOX_TRY_LOCK_PUT_FULL_FAIL,
    CMPES_ID_MBOX_TRY_LOCK_PUT_COPY_FAIL,
    CMPES_ID_MBOX_TRY_LOCK_PUT_COPY_FULL_FAIL,
    CMPES_ID_MBOX_CREATE_MUTEXATTR_INIT_FAIL,
    CMPES_ID_MBOX_CREATE_PROTOCOL_FAIL,
    CMPES_ID_MBOX_CREATE_MUTEX_INIT_FAIL,
    CMPES_ID_MBOX_PUT_FULL_WAITING_FAIL,
    CMPES_ID_MBOX_PUT_FULL_WAITING_MSGID,
    CMPES_ID_MBOX_PUT_FULL_WAITING_DEST_MODULEID,
    CMPES_ID_MBOX_PUT_MAX_SIZE,
    CMPES_ID_TIMER_TM_ALLOC_FAIL,
    CMPES_ID_TIMER_TM_EXPIRE_COPY_FAIL,
    CMPES_ID_TIMER_TM_INIT_NULL,
    CMPES_ID_TIMER_TM_INIT_MAXSIZE_FAIL,
    CMPES_ID_TIMER_TM_INIT_TABLE_FAIL,
    CMPES_ID_TIMER_TM_INIT_INTERVAL_FAIL,
    CMPES_ID_TIMER_TM_INIT_TIMERARRAY_NULL,
    CMPES_ID_TIMER_TM_INIT_HASHTABLE_NULL,
    CMPES_ID_TIMER_KILL_INDEX_FAIL,
    CMPES_ID_TIMER_TMSET_INDEX_FAIL,
    CMPES_ID_TIMER_TMSET_RUNNING_FAIL,
    CMPES_ID_TIMER_TMSET_MODULEID_FAIL,
    CMPES_ID_TIMER_TM_STATUS_FREELIST_COUNT_FAIL,
    CMPES_ID_TIMER_TM_STATUS_ALLOCLIST_COUNT_FAIL,
    CMPES_ID_TIMER_TM_STATUS_HASH_COUNT_FAIL,
    CMPES_ID_TIMER_TM_STATUS_FINAL_CHECK_FAIL,
    CMPES_ID_TIMER_TM_STATUS_ALLO_HASH_COUNT_FAIL,
    CMPES_ID_TIMER_ENTRY_TIMEOFDAY_FAIL,
    CMPES_ID_TIMER_ENTRY_TIMEINFO_FAIL,
    CMPES_ID_TIMER_ENTRY_READ_FAIL,
    CMPES_ID_TIMER_INIT_TM_FAIL,
    CMPES_ID_TIMER_INIT_CREATE_FAIL,
    CMPES_ID_TIMER_INIT_TIME_FAIL,
    CMPES_ID_TIMER_START_ENABLE_FAIL,
    CMPES_ID_TIMER_START_PARAM_FAIL,
    CMPES_ID_TIMER_CYCLE_START_ENABLE_FAIL,
    CMPES_ID_TIMER_CYCLE_START_PARAM_FAIL,
    CMPES_ID_TIMER_STOP_ENABLE_FAIL,
    CMPES_ID_TIMER_INTERNAL_ENABLE_FAIL,
    CMPES_ID_TIMER_RESTART_FAIL,
    CMPES_ID_RDKAFKA_PRODUCER_HEADER_FAIL,
    CMPES_ID_RDKAFKA_PRODUCER_SEND_FAIL,
    CMPES_ID_RDKAFKA_PRODUCER_QUEUE_FULL_FAIL,
    CMPES_ID_RDKAFKA_PRODUCER_CALLBACK_FAIL,
    CMPES_ID_RDKAFKA_COSUMER_THREAD_FAIL,
    CMPES_ID_AUTH_CHECK_CNT,
    CMPES_ID_AUTH_CHECK_FAIL,
    CMPES_ID_LOG_NOT_WRITE_COMPLETED_CNT_FAIL,
    CMPES_ID_INSUFFICIENT_FREE_SPACE_FAIL,
    CMPES_ID_EXCEPTION_LOG_INFORMATION_CNT_FAIL,
    CMPES_ID_MAX
}CM_PEX_Index_Type;

/***********Index partition of network error statistic counter***********/
typedef enum
{
    CMNES_ID_NETLIB_NONE_ERROR = 0,
    CMNES_ID_NETLIB_CONNECTION_TIMEOUT,
    CMNES_ID_NETLIB_CONNECTION_FAIL,
    CMNES_ID_NETLIB_BIND_FAIL,
    CMNES_ID_NETLIB_LISTEN_FAIL,
    CMNES_ID_NETLIB_SEND_FAIL,
    CMNES_ID_NETLIB_RECIEVE_FAIL,
    CMNES_ID_NETLIB_SOCKET_INVALID_FAIL,
    CMNES_ID_NETLIB_BUFFER_OVER_FAIL,
    CMNES_ID_NETLIB_SEND_BLOCK_FAIL,
    CMNES_ID_ARP_RSP_TYPE_FAIL,
    CMNES_ID_ARP_RSP_OFFSET_FAIL,
    CMNES_ID_ARP_TARGET_LENGTH_FAIL,
    CMNES_ID_ARP_TARGET_OFFSET_FAIL,
    CMNES_ID_ARP_SENDER_LENGTH_FAIL,
    CMNES_ID_ARP_SENDER_OFFSET_FAIL,
    CMNES_ID_ARP_SENDER_MEMCMP_FAIL,
    CMNES_ID_BUFFER_RESIZE_CAPACITY_FAIL,
    CMNES_ID_BUFFER_ADDSIZE_RESIZE_FAIL,
    CMNES_ID_BUFFER_ADDTCP_RESIZE_FAIL,
    CMNES_ID_BUFFER_ADDUDP_RESIZE_FAIL,
    CMNES_ID_BUFFER_ADDSCTP_MAX_CAPACITY_FAIL,
    CMNES_ID_BUFFER_ADDRAWIP_RESIZE_FAIL,
    CMNES_ID_FACTORY_UDPCONNECTION_UNVALID_FAIL,
    CMNES_ID_FACTORY_UDPCONNECTION_INITIALIZE_FAIL,
    CMNES_ID_FACTORY_ASFCONNECTION_UNVALID_FAIL,
    CMNES_ID_FACTORY_ASFCONNECTION_INITIALIZE_FAIL,
    CMNES_ID_FACTORY_TCPCONNECTION_UNVALID_FAIL,
    CMNES_ID_FACTORY_TCPCONNECTION_INITIALIZE_FAIL,
    CMNES_ID_FACTORY_SCTPCONNECTION_UNVALID_FAIL,
    CMNES_ID_FACTORY_SCTPCONNECTION_INITIALIZE_FAIL,
    CMNES_ID_FACTORY_RAWIPCONNECTION_UNVALID_FAIL,
    CMNES_ID_FACTORY_RAWIPCONNECTION_INITIALIZE_FAIL,
    CMNES_ID_FACTORY_TCPSERVER_CREATE_FAIL,
    CMNES_ID_FACTORY_SCTPSERVER_CREATE_FAIL,
    CMNES_ID_IPV4_PARSERIP_SIZE_FAIL,
    CMNES_ID_IPV4_PARSERIP_TOTAL_SIZE_FAIL,
    CMNES_ID_NETLIB_SOCKET_INIT_FAIL,
    CMNES_ID_NETLIB_PLATFORMIO_INITIO_FAIL,
    CMNES_ID_MANAGER_SENDDATA_FAIL,
    CMNES_ID_MANAGER_SENDSCTPDATA_FAIL,
    CMNES_ID_MANAGER_SET_CLIENT_CONNECTION_FAIL,
    CMNES_ID_MANAGER_BINDHANDLE_FAIL,
    CMNES_ID_MANAGER_FROMHANDLE_CONN_FAIL,
    CMNES_ID_MANAGER_FROMHANDLE_GET_FAIL,
    CMNES_ID_PLATFORMIO_INITIO_FAIL,
    CMNES_ID_PLATFORMIO_BIND_EPOLLCTL_FAIL,
    CMNES_ID_PLATFORMIO_BIND_EPOLLFD_FAIL,
    CMNES_ID_PLATFORMIO_UNBIND_EPOLLCTL_FAIL,
    CMNES_ID_CLIENT_ONRECV_SIZE_FAIL,
    CMNES_ID_CLIENT_INIT_SESSION_PROTOCOL_FAIL,
    CMNES_ID_CLIENT_INIT_SESSION_NULL_FAIL,
    CMNES_ID_CLIENT_CHECK_PACKET_NULL_FAIL,
    CMNES_ID_CLIENT_SEND_SESSION_FAIL,
    CMNES_ID_CLIENT_SEND_PACKET_LEN_FAIL,
    CMNES_ID_CLIENT_SEND_PACKET_DATA_FAIL,
    CMNES_ID_CLIENT_DISCONNECT_SESSION_FAIL,
    CMNES_ID_CLIENT_SETTCPHBPARA_SESSION_FAIL,
    CMNES_ID_CLIENT_PACKETLEN_MSGTYPE_ERR,
    CMNES_ID_SERVER_PACKETLEN_MSGTYPE_ERR,
    CMNES_ID_SERVER_ONACCEPT_FAIL,
    CMNES_ID_SERVER_ONRECV_FAIL,
    CMNES_ID_SERVER_INIT_RECEIVE_FUNC_FAIL,
    CMNES_ID_SERVER_INIT_UDP_HANDLE_FAIL,
    CMNES_ID_SERVER_INIT_TCP_HANDLE_FAIL,
    CMNES_ID_SERVER_INIT_PROTOCOL_FAIL,
    CMNES_ID_SERVER_SEND_CONN_FAIL,
    CMNES_ID_SERVER_SEND_PACKET_LEN_FAIL,
    CMNES_ID_SERVER_SEND_PACKET_DATA_FAIL,
    CMNES_ID_SERVER_SEND_UDP_VALID_FAIL,
    CMNES_ID_SERVER_SEND_SESSION_ISVALID_FAIL,
    CMNES_ID_SERVER_SEND_SESSION_LEN_FAIL,
    CMNES_ID_SERVER_SEND_SESSION_DATA_FAIL,
    CMNES_ID_SERVER_SETTCPHBPARA_SESSION_FAIL,
    CMNES_ID_TOOLS_FIND_IP_FAIL,
    CMNES_ID_TOOLS_GETALLIP_IOCTRL_FAIL,
    CMNES_ID_TOOLS_GETALLIP_SOCKET_FAIL,
    CMNES_ID_TOOLS_MAC_CONVERT_FAIL,
    CMNES_ID_TOOLS_READNI_RECV_FAIL,
    CMNES_ID_TOOLS_READNI_NLMSG_FAIL,
    CMNES_ID_TOOLS_PARSE_ROUTES_FAIL,
    CMNES_ID_TOOLS_GATEWAY_SOCK_FAIL,
    CMNES_ID_TOOLS_GATEWAY_SEND_FAIL,
    CMNES_ID_TOOLS_GATEWAY_READNL_FAIL,
    CMNES_ID_TOOLS_CREATE_SEM_FAIL,
    CMNES_ID_SOCKET_CREATE_ONLY_PROTOCOL_FAIL,
    CMNES_ID_SOCKET_CREATE_ONLY_SOCKET_FAIL,
    CMNES_ID_SOCKET_NONBLOCKING_FGETFL_FAIL,
    CMNES_ID_SOCKET_NONBLOCKING_FSETFL_FAIL,
    CMNES_ID_SOCKET_UPDATEINFO_INETNTOP_FAIL,
    CMNES_ID_SOCKET_UPDATEINFO_GETSOCK_FAIL,
    CMNES_ID_SOCKET_UPDATERAWIP_FINDIP_FAIL,
    CMNES_ID_SOCKET_UPDATERAWIP_SETSOCK_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_ONLY_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_UPDATERAWIP_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_INADDR_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_NONBLOCKING_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_INETADDR_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_SETSOCKET_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_UPDATEIPINFO_FAIL,
    CMNES_ID_SOCKET_CREATESOCKET_SETOPTION_FAIL,
    CMNES_ID_SOCKET_ACCEPTSOCKET_FAIL,
    CMNES_ID_SOCKET_DESTROYSOCKET_FAIL,
    CMNES_ID_SOCKET_SETSCTPOPT_GETSOCK_ADDR_FAIL,
    CMNES_ID_SOCKET_SETSCTPOPT_SETSOCK_ADDR_FAIL,
    CMNES_ID_SOCKET_SETSCTPOPT_GETSOCK_INFO_FAIL,
    CMNES_ID_SOCKET_SETSCTPOPT_SETSOCK_INFO_FAIL,
    CMNES_ID_SOCKET_SETSCTPHD_GETSOCK_ADDR_FAIL,
    CMNES_ID_SOCKET_SETSCTPHD_SETSOCK_ADDR_FAIL,
    CMNES_ID_SOCKET_SETSCTPHD_GETSOCK_INFO_FAIL,
    CMNES_ID_SOCKET_SETSCTPHD_SETSOCK_INFO_FAIL,
    CMNES_ID_SOCKET_RECVUDP_ERRNO_FAIL,
    CMNES_ID_SOCKET_RECVSCTP_ERRNO_FAIL,
    CMNES_ID_SOCKET_RECVTCP_ERRNO_FAIL,
    CMNES_ID_SOCKET_RECVRAW_ERRNO_FAIL,
    CMNES_ID_FACTORY_CREATE_SOCKET_FAIL,    
    CMNES_ID_MAX
}CM_NEX_Index_Type;



#endif


